### ISSUE TITLE
Flood correction requirement for ReflectometryReductionOneAuto

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#12524]
This issue was originally [TRAC 11686](http://trac.mantidproject.org/mantid/ticket/11686)

Need to check this with Tim, but I believe the idea is to allow a pre-division (done before anything else) of the TOF workspace by a flood workspace. The flood workspace is a single value per spectrum (integrated flood run).

This issue is split into the following tasks:

* [x]  #23212 Algorithm to create a flood workspace. + #23391 to make background fitting optional.
* [x]  #23318 Algorithm to apply a flood correction workspace.
* [x]  #23483 Add flood correction to RROA.
* [x]  #23520 Add flood correction settings to the GUI

**Comment by raquelalvarezbanos** [comment]
I discussed this with Jos yesterday, the idea is, as Owen mentions in the description, to add a pre-division before anything else is done. This is equivalent to what they do in their method `OurLoad` (in their `Sanity` module). The relevant bit of their script is:

```
    ########## Add code to norm to a flood ##########
    if FloodNorm==True and current_detector.nspec>1:
        if type(_dd) != mantid.api._api.WorkspaceGroup: # Make the for loop work even if _dd is not a workspace group
            _dd=[_dd,]
        # assume if ActiveFlood is in the framework we use it otherwise reduce it from a given run number and save it to the framework
        print 'Norm to Flood '+str(current_detector.name)
        print 'Norm to Flood '+str(current_detector.floodfile)
        _Active_flood=LoadNexusProcessed(current_detector.floodfile)
        #if current_detector.idf:
        #    LoadInstrument(_Active_flood, current_detector.idf, RewriteSpectraMap=False)
        _Active_flood=ConvertUnits(_Active_flood,'TOF')
        for i in _dd:
            _Active_flood=RebinToWorkspace(_Active_flood,i)
            #_dd=CropWorkspace(_dd,StartWorkspaceIndex=0)
            i=i/_Active_flood
            i=ReplaceSpecialValues(i,0.0,0.0,0.0,0.0)
```

**Comment by raquelalvarezbanos** [comment]
The issue of flood corrections is just one example of a general case where scientists need to apply a correction before processing the data. The idea is that scientists have a data set they save to disk for later use, this dataset has to be picked up and the correction applied before the reduction process. The question is how/where we should store it.  

Tim said that one idea was to make use of something similar to the script repository and that Jon Taylor showed interest in a global solution to this problem, so this work could be beneficial to ISIS/SNS/ESS. 

I am not sure how other groups/facilities would like to do this, but in a meeting with Jos we though that, for Reflectometry, an option would be to store this information in the Instrument Parameter File (given that the flood correction is basically a set of numbers, one per detector, indicating its efficiency, and therefore it is closely related to the instrument). @OwenArnold what do you think, would this be a good option?

**Comment by OwenArnold** [comment]
@raquelalvarezbanos before implementing anything for ISIS Refractometry, I would strongly suggest speaking to @Jon-Taylor and @granrothge about what their facilities requirements are for such cases. Putting information into the Parameter file is something I explored a few years ago when putting together [NormaliseByDetector](http://docs.mantidproject.org/nightly/algorithms/NormaliseByDetector-v1.html). I'm not sure that this was ever widely adopted. It would be better to do something that scales well across all facilities rather than working just for that technique area if possible.

**Comment by raquelalvarezbanos** [comment]
@gemmaguest This needs to be discussed with reflectometry scientist. We have to ask them how they would like to implement this (i.e. a new input workspace property in `ReflectometryReductionOneAuto`, a file specified in the parameter file, ...).

**Comment by gemmaguest** [comment]
Scientists at ISIS have agreed that they would a way to store flood files. They would like a new command to be able to create the flood file, and an option to save the file for reuse. The files will change from time to time so we need a secure and robust way to store multiple files and date-stamp them. We need to discuss within the Mantid team the best way to do this.

We need to decide on the best way to apply the corrections, e.g. straight after load. All reflectometry workflows at ISIS would require the flood corrections to be applied. The only time the correction would not be applied is when actually creating the flood file.

**Comment by gemmaguest** [comment]
Scientists have provided some more detailed information about how the flood files should be created and applied:

[Flood_corrections.zip](https://github.com/mantidproject/mantid/files/2265488/Flood_corrections.zip)

**Comment by gemmaguest** [comment]
All the child issues are now closed
