### ISSUE TITLE
Complex Shape Absorption Corrections Umbrella

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#12680]
- [x] Add ability to load STL files as mesh objects
 - [x] Add ability to position mesh objects within the geometry
 - [x] Make test script to validate using absorption corrections with simple mesh objects
 - [ ] Create script to assemble PEARL sample environment
 - [ ] Run MonteCarloAbsorption on sample environment.

PEARL scientists have provided some STL files for testing. Contact Chris Ridley@ ISIS

**Comment by samueljackson92** [comment]
Pascal indicated that this is currently low priority. He indicated that he wanted to perform absorption corrections on much more complicated shapes beyond what could be defined by hand. @NickDraper suggests we could do something such as limiting the flexibility of the shape geometry to be a fixed surface mesh when using a complicated shop defined from outside Mantid. More thought and discussion required when the time comes.

**Comment by samueljackson92** [comment]
@SamJenkins1 has been doing some work recently to handle this. `LoadSampleEnvironment` now allows us to load STL files and move them to there position.

**Comment by martyngigg** [comment]
The PEARL instrument scientists are going to provide us with CAD drawings of their various kits so that we can try to match the output from their own code for the corrections.
