### ISSUE TITLE
MuonAnalysis improvements

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#13096]
James Lord has suggested the following improvements/enhancements:
- [ ] 1. Be able to overlay asymmetry plots of two ( or more) periods from the currently loaded run on the same graph. (#15517)
- [x] 2. More arbitrary arithmetic to combine periods, for example 1+3-2-4 (#14020)
- [x] 3. Co-adding successive runs to improve stats (plain non period data too) (#13738)
- [x] 4. When changing period selection, at present it clears the fit curve off the graph. It would be nice to see how the old fit and new period compare. Similarly you could keep an old fit curve when loading the next run. (#16018, #16639)
- [x] 5. If fitting more than one period or combination from the same run, there's only one entry in the Results table. Should all of them be there, perhaps with an extra column for period number? (#15537)
- [x] 6. When adding two periods before analysis,  it should add the counts and then calculate the asymmetry. At present it appears to calculate asymmetries for each period and then add them. That makes it difficult to compare data when there are two Off periods and one On, for example. (#13102)
- [ ] 7. Another thing I’ve thought of. Periods can have names as set up in the DAE control in SECI, e.g. “Light on” or “RF off”. Can these appear in the Interface selector buttons in addition to numbers 1 to N? (#15738)

More improvements requested by muon scientists:
- [x] 7. Need to plot multiple groups in a tile format. Fit and data should be on one 'tiled' plot. (#15517)
- [ ] 8. Add a 'Squash' option in plot type (#15517)
- [x] 9. Need to fit multiple dataset on the fitting tab ('Data Analysis' tab). Suggestion:
  
  > - Option under Septup to fit multiple datasets
  >   > \* (In function browser) Need in function an additional column for sharing parameters between datasets and if not shared then the parameters could be under a tree.
  >   > \* (Section 'Data' in the browser) Need to think how we put this here maybe a list or how the data is stored?
  >   > \* Need to be able to tell the difference between squash and all groups fitting? (#15518)
- [ ] 10. Chisq for each would be nice to have too. As well as a global Chisq. (#15518)

This issue is to think about the best way to implement all the above requirements, create the necessary mockups, discuss the design with scientists and create new issues for each requirement.

**Comment by raquelalvarezbanos** [comment]
Issue #13102 has been created (item 6. in the list)

**Comment by raquelalvarezbanos** [comment]
The interface already allows users to co-add successive runs. However when this is the case, the run information is not correct (issue #13738 was created to fix this).

**Comment by tom-perkins** [comment]
Item 2 (arbitrary arithmetic to combine periods) is issue #14020, fixed in PR #14536

**Comment by raquelalvarezbanos** [comment]
I've updated the description so items can be marked as fixed. I've marked some of them as resolved, but we have to have a meeting with scientists to discuss the remaining ones. Issue #13738 mentioned above does not need discussion.

**Comment by tom-perkins** [comment]
Meeting held on 25/2/16.

- Item 9 (multi-dataset fitting) is a high priority, scientists will formulate use cases and we will circulate Balsamiq mockups for this
- One use case for this is doing fitting the same function to all periods in a run, perhaps with some shared parameters, and then using the sequential fit to repeat this for different runs. 
- Item 7 (tiled plots) is a popular request. It's useful to view data from all detectors, or all groups
- Item 1 (overlay) - Use a tickbox next to the "Plot" button to choose whether new plots are overlaid on the previous plots or not. It would be a commonly used option so put it here rather than in the Settings page.
- Item 5 - use the format `run number: period`, leave off the period for All or single-period data

**Comment by tom-perkins** [comment]
Tiled plots: for fit results, this is possible by using the new feature in #17434 to generate such plots on right-clicking a WorkspaceGroup.
Still need the ability to do this for the data before it is fitted.
