### ISSUE TITLE
Integrate ISIS powder diffraction scripts: umbrella issue

### ISSUE THREAD

**Issue by FedeMPouzols** [mantidproject/mantid#13404]
This is a growing and under development list of steps to do the first integration of the old ISIS powder diffraction scripts:

- [x] #13405 - Add ISIS powder diffraction scripts
- [x] #13407 - Add system test
- [x] #13408 - workflow
- [x] #13996 - preferences/settings
- [x] #13409 -  instruments other than HRPD

Note: I'm putting this initially for release 3.5, but I wouldn't expect this to be ready for 3.5. More realistically most of this work will be part of Mantid 3.6.

**Comment by FedeMPouzols** [comment]
I think that we can close this, as the original aim of #13409 has been fulfilled: we now support and have system tests for HRPD, GEM and POLARIS.

Longer term, as discussed in #13409, other instruments want to do powder diffraction: OSIRIS, VESUVIO. Check with Spencer and Sangamitra. There also seem to be rarely used diffraction scripts for TOSCA, IRIS and OSIRIS. So I'd leave #13409 open for these longer term issues.
