### ISSUE TITLE
Extend functionality of instrument view with PeaksWorkspace

### ISSUE THREAD

**Issue by MichaelWedel** [mantidproject/mantid#13908]
This results from a discussion with Pascal Manuel.

At WISH a common step is to use PredictPeaks to get a PeaksWorkspace with predicted reflections. This workspace is then dragged onto the instrument view, where the peak positions are indicated by small filled circles. Pascal suggested that it would be very useful to have an approximate indication for the expected peak intensity. This may also be useful for other single crystal diffractometers.

Implementing this requires several tasks that can be done independently:
- [x] Add CrystalStructure to Sample (#13905)
- [x] Create loader for CrystalStructure (#11268)
- [x] Modify PredictPeaks to use CrystalStructure from Sample if available and calculate structure factors (#13906)
- [x] Implement instrument view indicator (#13907)
- [ ] Implement Slice viewer indicator (share code with instrument view where possible). Slice viewer Peaks Viewer already provides an indicator for the integrated peaks. Worth discussion with Owen when it comes to it.

**Comment by martyngigg** [comment]
I believe this is now done as both the slice viewer and instrument view show the required information for single crystal peaks.
