### ISSUE TITLE
Umbrella: local&remote scripts for IMAT imaging

### ISSUE THREAD

**Issue by FedeMPouzols** [mantidproject/mantid#14155]
To keep track of the steps and components:
- [x] #14095 - aggregate energy bands
- [x] #12809 - run tomographic reconstruction tools
- [x] #14096 - pre-processing of input images for reconstruction
- [ ] #13468 - be able to save all intermediate pre-procesing steps

**Comment by DimitarTasev** [comment]
Issue noted in https://github.com/mantidproject/mantid/projects/3
