### ISSUE TITLE
Umbrella ticket for GetNegMuMuonicXRD Algorithm

### ISSUE THREAD

**Issue by MattKing06** [mantidproject/mantid#14346]
After reviewing the algorithm and custom dialog with Adrian Hillier, it has been decided that a few changes need to take place in the dialog:
- [x] Fix plotting of workspaces produced by algorithm (they are currently not plotting on their own) 
- [x] Implement the 'Keep Open' checkbox that we have on generic dialogs
-  [ ] Provide a way for the user to enter their own values for an element. If these are values for a new element then the button associated with that element should be enabled and it's values added to the dictionary.
- [x] Change maximum height of the dialog so that the periodic table can be seen in full when the dialog is first opened.
- [x] Make the y-position shift text-field into a spin-box to improve incremental shifts of plot.
