### ISSUE TITLE
Top 10 pylint offenders 

### ISSUE THREAD

**Issue by shahrozahmed1** [mantidproject/mantid#14705]
The top 10 files with most violations on pylint add up 707 violations even with the use of disables. 
![pylintviolationgraph](https://cloud.githubusercontent.com/assets/13132173/11594339/53d0046e-9aa1-11e5-9ff5-a58cd14417dc.png)

The most common violations for each top 10 file follows as:
![screen shot 2015-12-04 at 15 55 45](https://cloud.githubusercontent.com/assets/13132173/11594039/ba60cc38-9a9f-11e5-8e9f-961bd8fefe01.png)

Most of these violations are easy to fix especially once you have pylint running inside your editor, once # is closed you should also be able to follow the wiki page on `How To Run Pylint` on your editors. 

- [x] #14701  - Create a wiki page on how to run pylint locally
- [x] #14702  - decrease the number of pylint violations for top 10 **reflectometer** files
- [x] #14703  - decrease the number of pylint violations for top 10 **isis_reflectometer** files
- [x] #14704  - decrease the number of pylint violations for top 10 **SANS** & **TestViewer** files
- [x] #14738 - decrease the number of pylint violations for `isis_reduction_steps.py`

**Comment by shahrozahmed1** [comment]
This umbrella issue can be closed now that all the issues listed here have been resolved.
