### ISSUE TITLE
Detector Type for Irregular Geometries with v1. Instrument/Geometry

### ISSUE THREAD

**Issue by OwenArnold** [mantidproject/mantid#14965]
We have a [RectangularDetector](https://github.com/mantidproject/mantid/blob/master/Framework/Geometry/inc/MantidGeometry/Instrument/RectangularDetector.h) for banks, which are both topologically and geometrically regular. We are lacking an equivalent for detector banks that are topologically regular, but geometrically irregular. This is equivalent to a [vtkStructuredGrid](http://www.vtk.org/doc/release/5.0/html/a02055.html). This should allow us to define an irregular geometry without the full cost of specifying and evaluating shapes per individual detector.

The solution is to add a `StructuredDetector` to the Geometry and expose it for use via the IDF. A further step (another issue) will then be to work with the ESS to ensure that the detector geometry can be loaded quickly by writing an IDF for LOKI, which uses it.

The implementation should be done in this order.
- [x] Define additions to the xml for how you think this ought to be laid out. It might be worth looking at vtkStructuredGrid file formats. Get that agreed. #15532 
- [x] Create the in-memory representation `StructuredDetector`. #15542
- [x] Create a LOKI IDF using the above #15542
- [x] Evaluate and hone performance of the above #15793 

**Note**
This has been mentioned [here](https://github.com/mantidproject/documents/blob/Instrument-Geometry/Design/Instrument-2.0/requirements-v2.md), in the design document for v2 Geometry,
 but the time-scales for this are dependent on the changes to the core aspects of geometry and IDFs, which is likely to take a considerable about of time. I see no reason why this couldn't be added now to the existing v1. geometry. A prototype should help with downstream ESS integration.

Here's is Jon's sketch of the LOKI detector face:
![screen shot 2016-01-14 at 16 04 27](https://cloud.githubusercontent.com/assets/1109536/12329499/8eec5ab4-bad8-11e5-8847-e5d68545200d.png)

**Comment by OwenArnold** [comment]
As a further step, which should lead to a significant further speedup. We should allow the transformation of a rectangulardetector into a trapezoid (or some other configuration) using a change of basis operation. This could be done entirely in-memory. The only things you would need to know are the corners of the trapezoid in order to determine the change of basis matrix.
