### ISSUE TITLE
Top 15 untouched pylint offenders

### ISSUE THREAD

**Issue by shahrozahmed1** [mantidproject/mantid#15173]
Sequel to #14705 

The top 15 files which have not been touched on #14705 produce roughly 550 violations.
![capture](https://cloud.githubusercontent.com/assets/13132173/12787165/1be0b920-ca8c-11e5-8a40-066f09c30763.PNG)

As the previous issue #14705 has been a success and reduced around 400 Pylint violations, it is time to now reduce pylint errors from the new top 15 files which have not been touched in #14705 ; most of the files simply requires re-formatting, clean up and fixing minor pylint issues. User are able to set up pylint locally within their environment by using the following wiki page: http://www.mantidproject.org/How_to_run_Pylint 

- [x] #15169 - decrease the number of pylint violations for top 10 Refractometer files
- [x] #15170 - decrease the number of pylint violations for top 15 all SANS & reduction_gui files
- [x] #15171 - decrease the number of pylint violations for Inelastic and system test files
- [x] #15172 - decrease the number of pylint violations for tube & geometry_writer & main_window files

**Comment by shahrozahmed1** [comment]
All issues here have been fixed hence this umbrella issue can now be closed.
