### ISSUE TITLE
Imaging functionality and GUI for IMAT (release 3.7)

### ISSUE THREAD

**Issue by FedeMPouzols** [mantidproject/mantid#15558]
An umbrella for the IMAT related work that should be ready for release 3.7.
Includes at least:

- [x] #15666 Deal with rotation options properly in the GUI, and the local/remote scripts.
- [x] Other improvements for the stack of images viewer/selector: #13140, #12477 (make it work with MDImages).
- [ ] #14155 more pre-processing outputs in the local/remote reconstruction scripts (and other improvements). GUI and usability for this: #13469.
- [x] Improvements to FITS algorithms: #13887, #15873
  - [X] #15944 Save FITS.
- [x] Aggregation of energy bands available as Mantid algorithm in addition to the scripts already in place: #13839.
- [x] Good interface and additional features for energy bands: #13467.
- [ ] Corrections for MCP detector if we get mask information and tests: #13838.
- [ ] #15437 The MDImage workspace.
- [ ] Make best use of the MDImage workspace where the code is currently using traditional workspaces.
- [X] Updates in the GUI related to usability, settings, paths, etc. as the workflow and other details such as the transfer of files to/from the archive, SCARF, etc. are narrowed down.
  - [x] #15665 - update paths, options, and scripts to support different roots and components.
  - [x] #15666 - support rotation in the GUI.
  - [x]  #16048 - colors, etc.
- [x] A (big) round of documentation #11817.
- Keep up to date with new algorithms and versions of the tomographic reconstruction tools. #12790, #15971.
- Deal with the versions of tomographic reconstruction tools on the remote machines/SCARF.
- Modifications or improvements in the algorithms and workflow.
- Instrument definition issues.
- Support scientists with reconstruction benchmarks, algorithms, tests, analysis machine setup, etc.
- Support with files and their logs. In particular address issues with nexus files and files from different cameras/detectors.

**Comment by NickDraper** [comment]
Federeico, does this ticket need to be split into R3.7 and later release work?

**Comment by FedeMPouzols** [comment]
This one is specific to 3.7, there are two more roadmap tickets for 3.8 and 3.9: #15559, #15560.

**Comment by FedeMPouzols** [comment]
And I think that this one can be closed now, so I'm putting it "Reviewe Required".
Still not done: the IMDImage workspace.
