### ISSUE TITLE
Engg GUI: new functionality and improvements for release 3.7

### ISSUE THREAD

**Issue by FedeMPouzols** [mantidproject/mantid#15554]
An umbrella for the Engg GUI and related improvements  that should be ready for release 3.7.
Related longer-term umbrella issue: #13051 (check for additional tickets).
Includes at least:

- [x] Updates and improvements in the algorithms and workflow: #14788,  #13378, #13045, #15338.
- [x] Add algorithm EngFitDIFCFromPeaks: #15768
- [x] GSAS-II integration (peak fitting from powder diffraction) #15771, (old, GSAS 1: #10630).
- [ ] Graphical interface to use GSAS-II: #15552
- [x] Single peak fitting, higher level interface with plots: #15550.
 - [x]  Enable the single peak fitting for all banks: #15767
 - [x]  change of units for single peak fitting plot to dSpacing: #15766
 - [x]  enable the fitting tab to pick/select focused peaks: #15765 
 - [x] Enable single peak fitting for multiple runs. #15906 
 - [ ] Enable GUI to load the saved peak files
- [ ] Peaks diagnosis interface for calibration: #12927. Probably only for normal calibration (full calibration for later).
- [ ] GUI improvements, identified in bi-weekly meetings:
  - [X] avoid "spectrum ID" confusion #15529.
  - [X] fixes for cropped calibration with custom names #15466 
- [x] Refinements of the units and especially system tests. #14596.
- Modifications or improvements in the algorithms and workflow.
- Instrument definition issues.
- Support scientists and users. In particular address issues with nexus files and event mode experiments.

**Comment by NickDraper** [comment]
remaining issues tracked seperately, closed
