### ISSUE TITLE
Imaging functionality and GUI for IMAT (release 3.8)

### ISSUE THREAD

**Issue by FedeMPouzols** [mantidproject/mantid#15559]
An umbrella for the IMAT related work that should be ready for release 3.8.
Medium uncertainty about what will be the status and requirements.

- Get all details ready for first users.
- [ ] Visualization of sinograms and quick reconstruction slices (input/output)
- [ ] Start work to support MuhRec as tomographic reconstruction tool.
- [ ] Start work to support SAVU as one more tomographic reconstruction tool.
- [x] Implement at least one truly "local" reconstruction method that doesn't require any third party software, other than Mantid. #15971.
- [ ] Extensions and improvements to the MDImage workspace.
- [ ]  #14040 Some more improvements to LoadFITS (low priority, not required for now).
- Keep up to date with new algorithms and versions of the tomographic reconstruction tools.
- Support scientists with reconstruction benchmarks, algorithms, tests, analysis machine setup, etc.
- Modifications or improvements in the algorithms and workflow.
- Instrument definition issues.
- Corrections for MCP detector will probably need to be implemented and/or improved.
- Support scientists/users with reconstruction benchmarks, algorithms, tests, analysis machine setup, etc.
- Support scientists/users with files and their logs. In particular address issues with nexus files and files from different cameras/detectors.

**Comment by DimitarTasev** [comment]
Merged all issues in #17809. Closing this issue.
