### ISSUE TITLE
Complete VESUVIO transfer from VMS

### ISSUE THREAD

**Issue by NickDraper** [mantidproject/mantid#15600]
Elliot please add related tickets to this umbrella ticket

**Current Vesuvio Tickets are as follows:**

Core requirements for transfer from VMS:
* ~~#14305 - IP file to IDF~~ (moved to #15879)
* ~~#14924 - 2 and 3 period test data~~ (moved to 3.8 due no data being provided yet)
* [x] #14993 - Migrate Vesuvio content from scripts repo
* [x] #14994 - Rename workflow to commands
* ~~#15660 - Improve script interface~~ (moved to #15879)
* [x] #15661 - Investigate why fitting gets "stuck"
* [x] #15663 - Agree/validate outputs from scripts
* [x] #15816 - Addition of THICKNESS algorithm
* [x] #16039 - Intensity constraints bug

There may be additional issues to follow. I shall update the list as required

**Comment by martyngigg** [comment]
@ElliotAOram I think we need to have separate issues for the core transfer list vs the additional features list as I can see this thing just keeping growing.

Unless something is an urgent bugfix or just makes sense to do earlier then we should tackle all core requirements first before any of the additional requests. Can you spin out a separate issue for the additional features?

**Comment by ElliotAOram** [comment]
Good idea @martyngigg #15879

**Comment by NickDraper** [comment]
Elliot is this correctly targeted at r3.7?

**Comment by ElliotAOram** [comment]
All tasks list above are now complete or have been moved to the next release. This issue can be closed
