### ISSUE TITLE
Implement Crystal Field Parameter Fitting in Mantid

### ISSUE THREAD

**Issue by mantid-roman** [mantidproject/mantid#15684]
Implement in Mantid functionality of fortran program FOCUS which fits crystal field parameters of rare earth ions.

This issue is split into smaller tasks:
- [x] #15207 Translate into C++ the FOCUS subroutine that calculates energy levels and wave functions using Stevens operators.
- [x] #15699 Fitting function for peak positions and intensities.
- [x] #15700 Fitting function for a single spectrum.
- [x] #15701 Fitting function for multiple spectra.
- [x] #15702 Python interface.
- [x] #15703 Form factor correction.
- [x] #17517 Instrument resolution.
- [x] #15704 Initial parameters estimation.
- [x] #18133 Generate input for `EstimateFitParameters`
- [x] #18222 Multi-site intensity scaling ties.

**Comment by mantid-roman** [comment]
All tasks have been completed.
