### ISSUE TITLE
Vesuvio - Additional features to implement

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#15879]
Whilst completing the RoadMap issue for Vesuvio integration from the VMS (~~#15600~~) several additional requirements have also emerged that Matthew and Giovanni have requested:
Additional features requested:
- [ ] #14305 - IP file to IDF
- [x] ~~#14992 - Load Monitor algorithm property~~
- [ ] #15660 - Improve script interface
- [x] ~~#15729 - Vesuvio algorithms to start with Vesuvio prefix~~
- [x] ~~#15731 - Format for output workspace by running driver script~~
- [ ] #15764 - Vesuvio to use NormaliseByCurrent
- [ ] #15870 - Isolate mass and ConvertToYSpace in driver script

**Comment by martyngigg** [comment]
See #16864 for more current high-level tasks.
