### ISSUE TITLE
Further work on Data Processor Framework

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#16203]
Suggestions made by Owen:
- [ ] In `DataProcessorGenerateNotebook`, group objects into a struct. https://github.com/mantidproject/mantid/issues/16412
- [x] Move `DataProcessor{}` classes to a directory outside `Reflectometry`. https://github.com/mantidproject/mantid/issues/16413
- [ ] Pre-processing, processing and post-processing algorithms should not need to have all the algorithms registered. https://github.com/mantidproject/mantid/issues/16414
- [x] Make pre-processing/post-processing optional. https://github.com/mantidproject/mantid/issues/16415
- [x] Replace `shared_ptr`, use `unique_ptr` instead. https://github.com/mantidproject/mantid/issues/16416

**Comment by raquelalvarezbanos** [comment]
This is very low priority, only focus on this when you have no other relevant stuff to work on.

**Comment by gemmaguest** [comment]
Closing as we are no longer using the data processor in the restructured reflectometry GUI
