### ISSUE TITLE
Multi-dataset fitting: more beta bugs

### ISSUE THREAD

**Issue by tom-perkins** [mantidproject/mantid#16464]
*Reported by James Lord during beta testing*

- [ ] Set a parameter as *both* global and fixed. After fitting once, it loses the tie and is no longer fixed if you run the fit a second time --> see #16503
  - in general, ties and global flags can sometimes be lost after running several fits
- [x] Precision in "Edit parameter values": --> see #16492
  - Enter (e.g.) "20001.2345" and select "Fix" from the button on the right -- it chops off one decimal place
  - Enter an integer "23456" and do the same thing, it cuts off the last digit (2345)!
  - Values entered are rounded to fewer decimal places for display and the rounded values are used in the fit
- [x] "Add Workspace" dialog: workspaces are in random order, hard to find the one you want if there are a lot --> see #16462, #16496
- [ ] When a new workspace is added to the data selector, it should scroll to the bottom to show the new one added (makes it less likely to add one twice or skip one) --> see #16502
- [x] ~~Curves in graph: left/right go in the wrong order~~ (fixed in #16461)

**Comment by tom-perkins** [comment]
The plot guess curve (purple) can sometimes appear and disappear:
> After doing a number of fits I get the data, red fit curve (which looks OK), and green difference (0+-noise), however on stepping through the spectra a purple curve appears, changes a few times, and disappears again. These curves don't fit the data well at all, but could perhaps be the remains of earlier guesses or fit iterations. For any given data set it's the same set of purple spectra each time I step to it. What's going on?

>(This seems to only happen when I have "Plot guess" ticked.)

**Comment by tom-perkins** [comment]
The remaining issues here have been separated out into #16502, #16503 and so this issue can be closed.
