### ISSUE TITLE
Fit functions without documentation page

### ISSUE THREAD

**Issue by FedeMPouzols** [mantidproject/mantid#16480]
Every fit function should have a documentation page: http://docs.mantidproject.org/nightly/fitfunctions/index.html

There is no documentation for the following functions:
I've sectioned these out as best I can based on the history of the .h file.  Please create a pull request for each section.

- [ ] ComptonPeakProfile?, ComptonScatteringCountRate? GaussianComptonProfile? GramCharlierComptonProfile? (there is documentation for MultivariateGaussianComptonProfile)
- [ ] PoldiSpectrumConstantBackground, PoldiSpectrumDomainFunction, PoldiSpectrumLinearBackground, PoldiSpectrumPawleyFunction?
- [x] Polynomial #27412 
- [ ] MultiDomainFunction
- [ ] ReflectivityMulf
- [x] UserFunctionMD (there is documentation for UserFunction). #28328
- [x] FullprofPolynomial #28329
- [x] Bk2BkExpConvPV (but there is documentation for BackToBackExponential) #28331
- [x] ThermalNeutronBk2BkExpAlpha, ThermalNeutronBk2BkExpBeta, , ThermalNeutronBk2BkExpSigma, ThermalNeutronDtoTOFFunction (there is documentation for ThermalNeutronBk2BkExpConvPVoigt) #28330

You won't find the rst pages for these functions under: https://github.com/mantidproject/mantid/tree/master/docs/source/fitting/fitfunctions, so they are not found in the help browser or online pages.

Note that for some of these functions there might be old wiki pages.

For some of these functions (the groups with similar names) it may make sense as there is not much to say, but it would be good to have a documentation page that just states what is the exact difference with respect to the "base" function and link to it (if they are a product or convolution of the base with something else), or link to the important function if they are a component of a larger/more important function.

**Comment by NickDraper** [comment]
Assigned to me to split out to authors and volunteers

**Comment by ElliotAOram** [comment]
@NickDraper @FedeMPouzols I think Fick Diffusion is already there http://docs.mantidproject.org/nightly/fitfunctions/FickDiffusion.html

**Comment by FedeMPouzols** [comment]
@ElliotAOram: true. I might have added it by mistake. I've taken it out.

**Comment by FedeMPouzols** [comment]
Reopening this umbrella issue. I have marked in the description the functions that have been added.
