### ISSUE TITLE
Vesuvio Workflow Enhancements

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#16864]
Several issues/bugs exist in the current Vesuvio data treatment. This is a roadmap issue to define a set of tasks to improve the current vesuvio workflow for day-to-day data processing by users.

This supersedes ~~#15879~~ based on more recent discussions.

Tasks:
* [x] Enable multiple scattering correction for hydrogenous samples in backscattering (#20301)
* [x] Allow multiple scattering correction to be disabled from user scripts (#20056)
* [x] Reduce number of output workspaces generated by standard user scripts (#19483)
* [x] Add utility algorithms for prediction of widths & momentum distributions (#19223)
* [x] Merge Vesuvio diffraction with ISISIndirectDiffraction (#19175)
* ~~[ ] Improve performance of standard workflow~~
* ~~[ ] LoadVesuvio Resonance option (#15730)~~

**Comment by martyngigg** [comment]
Based on previous discussions the MS correction for hydrogenous samples was the key thing to completing the day-to-day requirements. The others were deemed nice to have.
