### ISSUE TITLE
Indirect Data Reduction - Indirect Resolution unit test

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#16892]
### Expected behavior
* IndirectResolution algorithm (like all other algorithms) should have a unit test.
### Actual behavior
* IndirectResolution.py currently does not have a unit test

### Platforms affected
* All

**Comment by ElliotAOram** [comment]
# Todo
* [ ] Add Testing file and update CMakeList
* [ ] Add success cases 
* [ ] Add failure cases

# To Test
* [ ] Run tests locally 
* [ ] Ensure tests pass on the build servers
