### ISSUE TITLE
Beta test feedback: Muon Analysis

### ISSUE THREAD

**Issue by tom-perkins** [mantidproject/mantid#17602]
*Feedback from beta testers for Mantid 3.7.20160922.1557, Windows*

**Higher priority** (aim to fix these for release)
- [x] *Fit to raw data* option doesn't work (most important point to fix) - #17605
- [x] Forgets selected groups on changing tab - #17619
- [x] Multilayer plot (tiled plot) - recognise muon fits and apply 'special' options - #17621
  - Data as points with errors, fit as line without points
- [x] Default label to run number - #17619

**Normal priority** (push back to 3.9)
- [x] "Sequential fit" checks the simultaneous fit label and warns if it's already used. But this label won't be used anyway, so there's no need to check it - #17619
- [ ] Automatically plot the tiled plot in the plot window after a simultaneous fit (may have to wait for #17511)
- [ ] Multiple results table: think of a better header than *f0*, *f1* for datasets
- [ ] Setting tie *f0.Phi=f1.Phi* caused a crash once (not second time) - try to replicate?
- [ ] Error message when entering a backward run range in sequential fit dialog e.g. 12345-43 (this is probably right, maybe the message should just be more descriptive)
- [ ] Check where start time is set

**Comment by tom-perkins** [comment]
All 3.8 issues have been merged and #17622 has been opened for the other tasks. Closing this issue as complete.
