### ISSUE TITLE
Muon Analysis: points from beta testers (for next release)

### ISSUE THREAD

**Issue by tom-perkins** [mantidproject/mantid#17622]
_Feedback from beta testers for Mantid 3.7.20160922.1557, Windows_

These are the lower priority points that were pushed back to release 3.9 (see #17602)
- [ ] Automatically plot the tiled plot in the plot window after a simultaneous fit (#17971)
- [ ] Multiple results table: think of a better header than f0, f1 for datasets (#17976)
- [x] ~~Setting tie f0.Phi=f1.Phi caused a crash once (not second time) - try to replicate?~~
- [ ] Error message when entering a backward run range in sequential fit dialog e.g. 12345-43 (this is probably right, maybe the message should just be more descriptive) (#17978)
- [ ] Check where start time is set

**Comment by tom-perkins** [comment]
(Can no longer reproduce the crash when setting ties)

**Comment by tom-perkins** [comment]
Separated out into separate issues, so there is nothing left in this issue. Closing as complete.
