### ISSUE TITLE
Umbrella: Work on NonOrthogonal Sliceviewer

### ISSUE THREAD

**Issue by lottiegreenwood** [mantidproject/mantid#18474]
Changes still required for sliceviewer:

- [ ] Non-orthogonal cursor

- [ ] Line viewer working in non-orthogonal mode

- [ ] Peaks viewer working in non-orthogonal mode (#18299)

**Comment by martyngigg** [comment]
This relates to the original MantidPlot slice viewer and is no longer relevant.
