### ISSUE TITLE
Stability issues related to reflectometry workflows

### ISSUE THREAD

**Issue by raquelalvarezbanos** [mantidproject/mantid#18830]
Reflectometry scientists have reported that stability is still a real problem for them. This umbrella issue is a group of stability issues either reported by reflectometry scientists themselves or developers working on/with reflectometry workflows. Although many of these will not be reflectometry-specific, the aim is to try to gather information that will enable us to focus fixes in areas that are likely to benefit them the most. 

Specific stability issues found:
- [x] #18944 Crash with Offspec data
- [x] #18951 Crash with Details button
- [x] #19075 Crash deleting data from GUI
- [x] #19103 Unexpected pixel ID crash
- [x] #19126 Crash when Load dialog is updating
- [ ] Jos has reported that on his Windows 7 machine Mantid is often very slow to start and sometimes seems to crash/hang while the splash screen is showing. We think this is due to network issues while mantid is downloading instrument files and that Windows is killing it if it takes too long. A suggestion to reproduce is to clear the .mantid/instrument directory and then start mantid with wifi enabled but no connection (e.g. on the STFC network but not logged in). Note that if you have no network connection at all mantid will not attempt to download files, so you have to con it into thinking there is a connection.
- [ ] Jos saw a crash on Becky's machine while running `LoadISISNexus` and `ConvertSpectrumAxis`. Has not attempted to reproduce.
  
This epic also includes several issues found by LSS developers.

**Comment by raquelalvarezbanos** [comment]
From Jos: see this [video](https://photos.google.com/share/AF1QipPRlAWg5gS7I6McTEEoOEdGXiqvS3qyXQGQxb8w5qr6_8skHdNBXOgNUgtzzJ9ftw?key=bkV1X2tIcGJtREpuaGowZkFnZUtFZU1Gd2RvZkJ3) for a typical failure.

**Comment by gemmaguest** [comment]
I'd like to keep this open because several child issues are still a problem
