### ISSUE TITLE
Corrections - Updating to Monte Carlo Absorption Corrections

### ISSUE THREAD

**Issue by louisemccann** [mantidproject/mantid#19985]
This is an umbrella ticket for all the changes required to update the current Indirect Absorption Corrections workflow to use Monte Carlo absorption.

Completed for Mantid 3.11:
- [x] update IndirectAbsorption algorithms - #18282
- [x] update documentation - #18723
- [x] update Indirect GUI - #18813
- [x] Split into [Shape]MonteCarlo - #19907 
- [x] Create[shape]Corrections - #20184
- [x] Unit tests, documentation etc

To-do in Mantid 3.12
- [x] Merge apply monte carlo with appy paalman pings - #21333
- [ ] Deprecate IndirectAbsorption algorithms
- [x] Split GUI into CalcualtePP, CalculateMC, and Apply - #20471, #21333

**Comment by brandonhewer** [comment]
All necessary components of this umbrella issue have now been complete.
