### ISSUE TITLE
Move HRPD to ISIS Powder

### ISSUE THREAD

**Issue by josephframsay** [mantidproject/mantid#20152]
- [x] Create the instrument class
- [x] Supporting files (eg. `hrpd_algs`, parameter maps etc)
- [x] Identify HRPD-unique steps
- [x] Implement HRPD-specific algs
- [x] Patch changes into the main flow
- [x] Add unit tests for any functions
- [x] Add a system test
- [x] Documentation
- [ ] ???
- [ ] Profit
