### ISSUE TITLE
ISIS SANS Rewrite List

### ISSUE THREAD

**Issue by AntonPiccardoSelg** [mantidproject/mantid#20265]
This is a umbrella ticket with items which we still need to implement for the ISIS SANS rewrite

## GUI

Points which the scientists raised were during our meeting on the 15th of August 2017:

- [x] Mechanism to check if the workspaces which have been specified exist. #21176
- [x] Add the`CompatilibiltyMode` to the User File #20524
- [x] Place reduction dimensionality radio button on the `Run` tab.  #20268
- [x] Provide a `Manage Directories` button as in the old GUI (need to check for a Python export) #21175
- [x] Maybe we need a load button to inspect the data (it is not clear if this is required) (only issue is async operation -> we can do this already see the `Display Mask` functionality)
- [x] Plot results check box which continuously shows the newest reduction result #21222 
- [x] Generic transmission monitor, not only M3 and M4 #20275
- [x] Have `thickness` available in the `Options` column #20268
- [x] Provide a `User file` column in the data table #20547
- [x] Provide a periods entry on the `Run` tab (maybe event `Options` column; speak to Rob about this)
- [x] Event slices should be in the `Options` column (Might not work with the DataProcessor Framework in the way the strings are parsed) #21255 
- [x] Add mask file to input on the `Mask` tab #20275
- [x] Provide a binning string input for the q conversion #20268
- [x] Add an `Add` tab to the GUI (again the only issue is async operation) #21096 #21097 
- [x] Add a `Beam Centre Finder` tab to the GUI (first need to implement `Beam Centre Finder`)
- [x] Enable instrument view of masked data #20283
- [x] Add option to save out SANS state on the diagnostic tab (suggestion from Martyn)
- [x] Provide diagnostic output, ie put the transmission workspaces (fitted and unfitted) on the ADS if this is requested by the user. We should have a checkbox for that. This should not be too complicated, needs to pass the workspaces up from the `SANSCalculateTransmission` algorithm to the batch script. There the batch script needs to name the workspaces correctly and put them on the ADS. Alternatively this could happen in `SANSCalculateTransmission`. In this case we need a way of supplying the transmission output names to the algorithm. #21017
- [x] Allow for processed Mantid files to be used for the reduction input. Currently we only support nexus from the machine (single and multi period), raw from the machine and added data. Diego would like to process some data and then pass it to the reduction. The main locations where changes are required are `load_data.py` and `file_information.py`. It is important that scatter sans data is loaded in a way that the data and the monitors are loaded into separate files. If this can be achieved easily, then this should not be a problem. I assume the main thing is to have a check if the loaded data contains both data and monitors. #21223 
- [x] Currently in the new sans GUI there is column after each work-space name  which is used to specify the period. Make this optional so that it is not cluttering up the GUI when it is not needed. #20748 
- [x] The thickness is a common cause of error among users so add it to it's own column
- [x] Make process button more obvious #21531
- [x] Move instrument selection to top/make more prominent #21531
- [x] And the ‘wavelength’ box moved from General to Q, and the Phi and Radius boxes moved from Mask to Q.
- [x] Change dimensionality box to reduce.

## Backend

- [x] Create the `Beam Centre Finder` #20822

**Comment by Mantid-Matthew** [comment]
These are all done
