### ISSUE TITLE
Large number of Flake8 complexity warnings

### ISSUE THREAD

**Issue by josephframsay** [mantidproject/mantid#20508]
This is an umbrella issue for the 41 warnings for too much cyclomatic complexity in Python scripts in the build servers. These should be reduced as much as possible. The following is a list of all the areas where these warnings occur, and how many warnings they cause.

- [x] Framework/PythonInterface/plugins/algorithms (5)
- [x] Framework/PythonInterface/plugins/algorithms/WorkflowAlgorithms (4) #20637 #20530  
- [x] Testing/SystemTests/tests/analysis (1) #20637 
- [x] scripts/Calibration (1) #20637 
- [x] scripts/DGSPlanner (1) #20637 
- [x] scripts/HFIRPowderReduction (1) #20637 
- [x] scripts/Inelastic/Direct (5)  #20551
- [x] scripts/Interface/reduction_gui/reduction/reflectometer (1) #20663 
- [x] scripts/Interface/reduction_gui/reduction/toftof (1) #20635 
- [x] scripts/Interface/reduction_gui/widgets/reflectometer (1) #20663 
- [x] scripts/Interface/ui/reflectometer (2) #20663 
- [x] scripts/LargeScaleStructures (1) #20637 
- [x] scripts/Reflectometry/isis_reflectometry (2) #20663 
- [x] scripts/SANS (8) #20530 
- [ ] scripts/reduction (2)
- [x] scripts/reduction/instruments/inelastic (3)
- [x] scripts/reduction/instruments/reflectometer (1) #20663  
- [x] tools/reports (1) #20637 

A number of warnings in #20530 and #20663 were not fixed, but suppressed with a `noqa` flag. This was deemed acceptable, as these scripts are very complex, untested and soon to be deprecated, so refactoring them is needlessly risky.

**Comment by mganeva** [comment]
@josephframsay could you please update the line about TOFTOF GUI to
`scripts/Interface/reduction_gui/reduction/toftof (1)` #20635?

**Comment by josephframsay** [comment]
@mganeva done - thanks for your help on this!

**Comment by martyngigg** [comment]
@josephframsay Is this meant for `3.12`?

**Comment by josephframsay** [comment]
Yup - changed!

**Comment by ElliotAOram** [comment]
Flake8 warnings from the algorithms section can  not be resolved until proper unit tests have been written. Issues have been opened to this affect see:
#20861
#20764

**Comment by josephframsay** [comment]
Flake8 warnings from `scripts/reduction/reducer.py` were not resolved as the file has no unit tests on it. An issue has been open at #20863 to address this.

Other than that and `LRReflectivityOutput`, all files have either been refactored sufficient to make the warnings go away, or issued with a `noqa` flag to suppress the warnings on the build server. This has only been done in the case of files which are to be deprecated soon and have insufficient tests, making refactoring needlessly risky.

Once all the relevant PRs have gone through the cap on the Flake8 build server should presumably be lowered to the number of outstanding issues , which I think is 3.
