### ISSUE TITLE
New POLARIS requirements

### ISSUE THREAD

**Issue by josephframsay** [mantidproject/mantid#20603]
Following a round of beta testing with POLARIS, the following extra requirements were drawn up:

- Adjust some default parameters
    - [x] `sample_empty_scale` to 1
    - [x] mode-specific cropping values TBC
- [x] Output non-splined vanadium by default
  - [x] Add this to the system test
- [x] Fix a slight error in the documentation
- [x] Change `masking_file_name` to `vanadium_peaks_masking_file`
- [x] Add suffix to output file names
  - [x] Add test to this feature
- [x] Prefix `s01` etc to `.dat` files in the same way as the GSAS and Nexus files
  - [x] Test this
