### ISSUE TITLE
New PEARL requirements for ISISPowder

### ISSUE THREAD

**Issue by josephframsay** [mantidproject/mantid#20851]
Following discussions with PEARL, some requirements for the next cycle were drawn up:

- [ ] Add `.cal` file creation to the library. This is mostly implemented already in `pearl_calibration_algs.py`, but will need wiring up and refactoring
  - Also investigate what POLARIS do about their `.cal` files - I'm pretty sure they just use the same one for each cycle, but maybe they'd like to be able to generate them as well
- [ ] Investigate problems with vanadium calibration
  - Intensity too high - possibly something should be divided but isn't?
  - The dip at the tail end of the data is still there - David thought he'd solved this, but there doesn't appear to be a paper trail

David also left a few `todo`s, which could do with clearing up
- [ ] `pearl.py:128` - Move generating absorption corrections to an instrument param
- [ ] `pearl_algs.py:53` - Are these values applicable to all instruments?
- [ ] `pearl_algs.py:121` - Move hardcoded spline values into adv. config
- [ ] `pearl_calibration_algs.py:8` - This entire file needs cleaning and refactoring
- [ ] `pearl_calibration_algs.py:54` - Fix all of this as the script is too limited to be useful

**Comment by josephframsay** [comment]
Closing as each item is taken care of in more specific issues (#20866 and #20877)
