### ISSUE TITLE
Total Scattering Umbrella issue

### ISSUE THREAD

**Issue by ElliotAOram** [mantidproject/mantid#20864]
This issue will act as an umbrella for ALL the development of the Total Scattering support within Mantid. See required features below:
* [x] **Setup**
  * [x] Define instrument/beam parameters/ calibration file (This will most likely exist in Mantid already) `LoadDiffCal` and `SetSample`, but don't have beam dimensions
  * [x] Define grouped datasets for: Vanadium, Sample, Sample background, Containers `AlignAndFocusPowderFromFiles`, needs extra parameter for adding/subtracting a correction pixel-by-pixel
  * [x] Define sample properties: Composition, density, dimensions, temperature `SetSample`
* [ ] **Pre-corrections**
  * [x] Merge and group data into banks (grouping file) `AlignAndFocusPowderFromFiles`
  * [ ] Normalise to incident monitor `NormaliseToMonitor` - Incident = 1, Transmission = 2
  * [x] Normalise sample and container(s) to vanadium `Divide`
  * [ ] Correct for multiple scatter (not yet possible)  #20235 and attenuation `ApplyPaalmanPingsCorrection` (needs umbrella issue)
  * [ ] Normalises sample to number and type of atoms - need algorithm to use beam information and `SetSample`
* [ ] **Workflow**
  * [x] Convert from TOF to Q - `ConvertUnits`
  * [x] Calculate self scattering and perform Placzek correction for inelasticity - @marshallmcdonnell has a prototype for calculating the correction and determining the incident spectrum
  * [ ] Calculate free gas scattering law for inelasticity
  * [x] Merge banks into single structure factor by `MatchSpectra` ~~#23613~~, `SumSpectra` ~~#23343~~, `CropWorkspaceRagged` ~~#21488~~, and `RebinRagged`
  * [x] Perform Fourier transform `PDFFourierTransform` - has Lorch, needs thermal damping
  * [ ] Inverse packing fraction and packing fraction
  * [ ] Normalisation correction factor - *This was originally an option in Gudrun and is an arbitrary scale factor (which shouldn't be required)*
  * [ ] Normalisation option `<b_coh>^2` - add methods to `Material`
  * [ ] Top hat function - convolution of top hat function with data to create a "smeared out version" of function for background subtraction - Soper 2009
  * [ ] Fourier transform real space to reciprocal space
  * [ ] Fourier Filter - Minimum radius
  * [ ] G(r) broadening - Lorch function (liquids) and thermal damping
  * [ ] Find first "Real" peak
  * [x] Subtract low-r region from Q space data (everything before first real peak) - range for subtraction is user specified
  * [ ] Fit low-Q region and evaluate for extrapolating S(Q)
* [ ] **Cleanup**
  * [ ] Output the Q and r space data as ascii files suitable for PDFgui `SavePDFGui` and RMCProfile (need description of the format)

Related: #22556

**Comment by marshallmcdonnell** [comment]
Still WIP
