### ISSUE TITLE
Issues with Engineering Diffraction GUI

### ISSUE THREAD

**Issue by josephframsay** [mantidproject/mantid#21022]
This is an umbrella issue to address the problems identified with the Engineering Diffraction GUI.
- [x] Confusing pop-up message on startup #20993
- [x] Stalling/slow algorithm execution with no progress updates #21067 
- [ ] Dump data in d-spacing as well as TOF (low priority, they can use ConvertUnits)
- [x] Select peak does not work on the fit tab #21355 
- [ ] No option to select peak functions on the fit tab
- [x] No way of selecting several files on the fit tab #21164 #21273 #21302
- [ ] IMAT need a background correction option (low priority)
- [x] Add new tab for refinement via GSAS (old issue at #15552)
- [x] Export log files to HDF/XML format (possible related old issue at #17168) #22350 #22354 #22357
- [x] User output directory is only used for focus, not fitting (or calibration?) - (there are some notes on this in #21226) #22361
- [x] X axis label is always D, but plotted data is sometimes in TOF #21273 
- [x] Cannot remove runs from model #21376
- [x] Once a fit has been run, you can't plot the relevant workspace without plotting the fit results #21384
- [ ] Texture (as opposed to bank) grouping - possibly low priority (old issue at #16695)

To see a list of old issues Fede created for the GUI, go [here](https://github.com/mantidproject/mantid/issues?q=is%3Aopen+is%3Aissue+author%3AFedeMPouzols+label%3A%22Component%3A+Diffraction%22+label%3A%22Component%3A+GUI%22). Some of them are a bit out of date, and I've referenced a few in the above list, but it'd be a good thing to keep an eye on all the same (particularly #15371 once the features are taken care of).

**Comment by SamJenkins1** [comment]
The issues described here are either no longer relevant or fixed with the exception of selecting peak function on the fitting tab which I will add a new issue for.
