### ISSUE TITLE
New requirements for HRPD

### ISSUE THREAD

**Issue by josephframsay** [mantidproject/mantid#21148]
Following an introduction to `isis_powder` with HRPD, a few extra requirements were identified

- Extra TOF windows - HRPD use two windows we weren't previously aware of, **10-50** and **180-280** #21197
  - [x] Add these to the HRPD class
  - [x] Work out window-specific cropping values
  - [ ] Validate these with HRPD
- [x] Config files never made it through to the API - wire things up so we can use one #21144  
- [x] Investigate how more complex chemical formulae are handled, and whether `SampleDetails` needs to be changed to handle them
- [ ] Make scripts get the TOF window from run if they can instead of relying on the user passing it

**Comment by josephframsay** [comment]
All items either resolved or covered in an issue of their own
