### ISSUE TITLE
Indirect - Data Analysis - Multi-data set QENS fitting Umbrella

### ISSUE THREAD

**Issue by brandonhewer** [mantidproject/mantid#22303]
This is an umbrella issue for all issues regarding the development of the QENS fitting algorithms and interfaces (Indirect > Data Analysis) towards multi dataset fitting functionality.

- [x] Modify existing QENS sequential fitting algorithms (ConvolutionFitSequential, IqtFitSequential, MSDFit) to allow for multiple datasets to be provided as input, in the same fashion as the PlotPeakByLogValues algorithm. (#22034)
- [x] Create QENS simultaneous fitting algorithms, which are capable of taking multiple datasets as input. (#22056)
- [x] Adapt the existing Indirect Data Analysis interface code into the MVP pattern.  (Issues: #22064)
- [x] Provide the option to select whether to perform a sequential or simultaneous fit in the QENS fitting interfaces.
- [x] Provide the option to select discontinuous spectra ranges in the QENS fitting interfaces (Indirect > Data Analysis). (Issue: #22064)
- [x] Add a data selector table-based widget to the QENS fitting interfaces along with the option to select the active workspace (see `General > Multi dataset` fitting for an example). It should be possible to switch between this mode and the current single dataset fitting mode.

**Comment by robertapplin** [comment]
Closed as this is mostly done, or is being done and is documented by a different issue.
