### ISSUE TITLE
Project Recovery - Roadmap

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#22715]
High Priority:
- [x] Race condition in ADS : #22714 
- [x] Remove checkpoint files on graceful exit
- [x] Deadlock when closing Mantid with large history in debug mode
- [x] Sanitise `#` characters (See issue #23248)
- [x] Instead of using the ws namessz, we should save them using a counter (See issue #23258)
- [x] Save algorithms are written in the resulting history (and the timestamp does not match the expected format)
- [x] Handle grouped workspaces (See issue #22922) 
- [x] Project saving should start up after refusing project recovery when offered.
- [x] Handle situations where strings are passed rather than workspaces. The history of the workspace that was passed as a string should also be added to the history of the 'parent' workspace. (See Issue #23450)
- [x] Add the ability to call a save from MantidPlot for testing and general purpose (See Issue #23468)
- [x] Unit tests for project recovery (See issue #23564)
- [x] Since multiple instances have been merged to master, file not found exceptions are becoming annoyingly common place (See issue #23739)
- [x] Fix workspace history to stop it recording duplicates of split of workspaces later on, when appending new workspace history.  (See issue #23748)

Normal Priority:
- [x] After incomplete recovery, offer options to use previous checkpoints, retry, go to script or just don't (See issue #23570)
- [x] Add lock file whilst writing to project recovery folder, so we can check for a complete write (See issue #23728)
- [x] Recovering when multiple instances on Mantid are running (See issue #23494)
- [x] Load in the GUI using a `Yes` option on project recovery
- [x] Check saving is restarted after recovery completes
- [x] Workaround ADS race conditions properly
- [x] Project recovery does not start autosaving when you select no when it pops up, or it fails to load successfully.
- [x] Project recovery has problems when a workspace group is passed to an algorithm that takes an individual workspace. (See issue #23265)
- [x] Project recovery should handle groups properly (Ref: PR: #23303 and issue ) as this was removed to fix an issue with crashing until it can be handled in a nicer way, currently, it is handling by removing group workspaces and not regrouping them on recovery. 
- [x] Sanitise config options
- [x] Add Project Recovery options to the preferences in mantid

Low Priority
- [X] Sanitisation of workspace names to deal with two workspace names that differ only in special characters eg `Work\\space` != `Work\space`
- [x] Make sure project recovery works with `Rename` of Group Workspaces (Issue #23304)
    - Bring up point that running RenameWorkspace and RenameWorkspaces only renames the group's head name
- [x] Make sure if saving a group workspace to check if it empty, if it is then ignored (this shouldn't normally happen but has happened once so we shall fix it as it stopped a saving thread) (See issue #23901)
- [x] Come up with a graceful way of dealing with live data (See issue #22825)
- [x] Stop script builder displaying logs when called via project recovery

**Comment by Pasarus** [comment]
Supposedly complete
