### ISSUE TITLE
Use ReflectometrySumInQ in ReflectometryReductionOne

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#23011]
The Q summation done in `ReflectometryReductionOne` is now available as the separate algorithm `ReflectometrySumInQ`. We should be able to remove this code and call `ReflectometrySumInQ` as a child algorithm instead.

However there are a few things to check:
- [ ] #30191 The 2theta pixel size is calculated as the difference between adjacent centres, rather than bounding box size. Our scientists would prefer to continue to use the latter (although it makes little difference with our current instruments, it should technically be more correct). We'd therefore like to add an option to `ReflectometrySumInQ` to use this.
- [ ] #30189 We currently pass `ThetaIn` to provide the horizon angle rather than passing a `BeamCentre` pixel and using its 2theta/2. I think we will need to add a `ThetaIn` property to `ReflectometrySumInQ` (such that either `ThetaIn` or `BeamCentre` must be provided but not both). I don't think we can use `BeamCentre` because we don't have that information available in our workflow (although it could be found through fitting, which we may want to do in future, but we may still want the option to override it).
- [ ] #30192 The `BeamCentre` is currently also used as the reference 2theta that the projection is done onto. This should be arbitrary though so we should be able to use e.g. the centre of the ROI instead if `BeamCentre` is not given.
- [x] #30235 To use a different reference 2theta we'll need to use RefRoi instead of ConvertUnits for the final conversion to Q in RRO
- [ ] #30190 There is an error in the projected wavelength range in RRO which needs to be fixed to give consistent results with RSIQ.

We should also first complete:
- [x] #14000 to use a consistent way of specifying the workspace indices

**Comment by gemmaguest** [comment]
There are ongoing discussions with scientists at ISIS about how we can consolidate this

**Comment by gemmaguest** [comment]
Closing as stale because we are unlikely to have resource for this any time soon
