### ISSUE TITLE
EPIC: Fix RRO workflow algorithm history

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#23012]
**Original reporter:** Jos at ISIS

`ReflectometryReductionOneAuto` should be a [workflow algorithm](http://docs.mantidproject.org/nightly/concepts/WorkflowAlgorithm.html) but has some issues which mean unrolling its history is not possible.

- [x] #28935 to remove the calculation in the `convertToQ` function and use a child algorithm instead, so it is visible in the history.
- [x] Move reflectometry specific algorithms to their own directory `Framework/Reflectometry` 
- [x] #34293
- [x] #28638 
- [x] #23011

As part of this it may be necessary/beneficial to sort out some inconsistencies in the way output workspaces are handled:
- [x] #27633 Add proper output properties rather than dumping workspaces into the ADS part-way through algorithms.
- [x] Add output properties for all outputs of RROA i.e. output transmission workspaces.
- [x] Only enable optional outputs if they will be used e.g. enable IvsLam only if Debug is set to true.
- [ ] Remove the hack where IvsLam is always output if the input is a workspace group. This is done because IvsLam is needed for polarization corrections, but we should be able to get it from the child algorithm without it needing to be a final output. The behaviour at the moment is confusing so I'd like to fix this.
- [ ] I think it's harder to remove a similar hack from the GUI where IvsQ is always output because `Stitch1DMany` takes a list of names rather than workspaces. We probably need to do a clean-up afterwards to fix this - it's probably best to add a wrapper algorithm to handle it. We could fix it in ReflectometryReductionOneAuto, though, and then run this as a child algorithm so we can get it in the GUI code. The GUI will then need to store it in the `Row` so that it is available for the postprocessing algorithm. It may be better to wait until we have proper support for passing vectors of workspaces to algorithms before we look at this. It's not high priority.

**Comment by gemmaguest** [comment]
Closing as stale

**Comment by gemmaguest** [comment]
Re-opening because with the focus on ORSO creating a new standardised nexus output, along with Polref requiring more reproducible history from the GUI, this will become more important
