### ISSUE TITLE
ISIS Reflectometry Interface - Runs Tab Tidying

### ISSUE THREAD

**Issue by edwardb96** [mantidproject/mantid#23027]
*This issue refers to work which should be based on changes currently only present in the branch `isis_reflectometry_alternative_table`.*

### Main tasks
- [x] (Pr #25730) Currently, for autoprocessing we handle polling/diffing the list of runs explicitly in
      `RunsTabPresenter` this makes it more difficult to mock out and test the arrival of new runs.
      If we move this out into a new class, `CatalogRunNotifier` an implementation of a new
      interface `RunNotifier` which is injected into the presenter either as a parameter (or if
      necessary a factory which takes the session details as a parameter) then this becomes possible.
      This should probably also be the new home for the `metadataFromDescription` method.
      *Estimated time*: 2-3 days
      *Required for*: Autoprocessing.
- [x] (PR #25798) Updating of the RunsTable progress bar needs to be implemented.
- [x] (PR #25843) Reduction options for live data monitor need to be set
- [x] (PR #25851) Q range in table needs to be updated from algorithm output values
- [x] (PR #25897) Implement catalog login (see below)

#### Must have
- [x] Auto-saving a row with a GroupWorkspace output causes an unhandled exception (this is an existing bug but previously did nothing).
- [x] Cut/copy/paste bugs: Cutting and pasting does not update the model and causes crashes down the line; pasting onto an incorrect depth/size should be disabled; pasting groups should use a unique group name
- [x] Disable editing keys while processing (editing the table while processing can cause a crash)
- [x] Disable the Generate Notebook option - this is not currently used so not required for the initial implementation
- [x] Change Ctrl-Enter shortcut (to add a new group) because this clashes with the shortcut to run a script in workbench
- [x] CorrectDetectors and NormaliseByIntegratedMonitors should default to true but they default to false

#### Should have
**General**
- [x] Row highlighting is lost during processing
- [ ] Disabled icons should be greyed out

**Table**
- [ ] Add a group and row when the GUI starts
- [ ] Add an empty row to the empty group when the table is cleared
- [ ] Remove the empty group when starting autoprocessing

**Search**
- [x] #25970 Fix catalog login for workbench (CatalogLoginDialog fails)
- [ ] Autoprocessing should not start if catalog login fails or if the search string is empty.

**Code Quality**
- [ ] Documentation should be checked and updated where necessary, particularly new keyboard shortcuts
- [ ] Unit tests are missing for cutting and pasting rows in the runs table
  - Notably Clipboard.h
- [ ] Unit tests are missing for default Instrument and Experiment options when not in the instrument parameters file
- [ ] As noted on PR #25798 it would be good to move `ModelCreationHelper` to a `TestHelpers` subdirectory.

### Implementation tasks
- [x] Build an interface around the `runPythonScript` method, `PythonRunner`, implement it for
      `QtReflMainWindowView` and pass in the instance when creating the `ReflRunsTabPresenter`. This
      seems like the cleanest way to enable running python code without having all presenters know
      about the parent view and it's ability to run python code. I believe a technique like this is
      necessary for plotting until Mantid 4, but we may be able to avoid it completely for `CatalogLoginDialog`,
      this would require some further investigation and potentially hacking in `AlgorithmDialog`. 
      *Check if still required first* e.g. we want to get rid of catalog login in #14369
      *Estimated time*: 1 day for first suggestion using `PythonRunner` interface implemented by `QtReflMainWindowView`.
      *Required for*: Plotting, ICat Login.
- [x] I'm not sure it's worth trying to MVPify the search section, this seems to have been kept reasonably
      separate, some of the ICat stuff in `ReflRunsTabPresenter` should be moved out into it's own
      class.
    *Estimated time*: Assuming search section is left alone, a couple of hours, requires further investigation.
    *Required for*: Autoprocessing.
- [x] Remove the `getPresenter` method left behind from MVC.
     *Estimated time*: Less than an hour.
     *Required for*: Cleanliness.
- [x] Move away from old style `notify(Flag)` interface to use of separate methods.
     *Estimated time*: Less than an hour.
     *Required for*: Cleanliness and Readability.
- [x] Finally rename and move the files into correct directory structure, updating any include paths as necessary.
     *Estimated time*: Less than an hour.
     *Required for*: Cleanliness and Readability.

**Comment by marshallmcdonnell** [comment]
Just thought I would suggest this for the Jupyter Notebook stuff: https://github.com/mwouts/jupytext

**Comment by gemmaguest** [comment]
Closing this issue as remaining tasks have been consolidated into #26025
