### ISSUE TITLE
ISIS Reflectometry Interface - Save Tab Tidying

### ISSUE THREAD

**Issue by edwardb96** [mantidproject/mantid#23032]
*This issue refers to work which should be based on changes currently only present in the branch `isis_reflectometry_alternative_table`.*

There is some ambiguity around how to handle log parameter selection and how to update the
list of workspaces.

We may be able to filter the list of workspaces down to just those reduced in the current
session/batch but careful consideration is required for handling workspaces which have been
renamed/deleted.

Work performed for #22297 may require changes or updates the way this tab works under the hood.

**Tasks**
- [ ] Add model detailing the selected log parameters, the `FileFormatOptions` and the
      save algorithm name should be turned into a model which has save operation/s which perform a
      similar role to ReflAsciiSaver. This should be synchronized with the view when the settings
      are changed.
      *Estimated time*: A couple of hours.
      *Required for*: Autoprocessing with automatic save.
- [ ] The save tab has had some previous work with has upgraded it to using the 'subscribe' style.
      However, all notifications are still being shoehorned into one method and using a switch
      statement to separate out again in the presenter. This should be updated.
      *Estimated time*: Less than an hour.
      *Required for*: Cleanliness and Readability.
- [ ] The for loops in `getSelectedWorkspaces` and `getSelectedParameter` which convert from
      `QStringList` to `std::vector<std::string>` should be converted to calls to `map`.
      *Estimated time*: Less than an hour.
      *Required for*: Readability.
- [ ] The error handling for ReflAsciiSaver/it's replacement should be improved, eliminating exceptions
      for non-exceptional cases and avoiding the need for `catch(...)`.
      *Estimated time*: Less than an hour.
      *Required for*: Cleanliness and Readability.

**Comment by gemmaguest** [comment]
Closing because this is low priority and we are unlikely to get around to it. It was a developer suggestion rather than a request from users.
