### ISSUE TITLE
ISIS Reflectometry Interface - MVPification

### ISSUE THREAD

**Issue by edwardb96** [mantidproject/mantid#23051]
*This issue refers to work which should be based on changes currently only present in the branch `isis_reflectometry_alternative_table`.*

Ongoing work to integrate `JobTreeView` in the ISIS Reflectometry GUI requires tabs holding information pertaining to a particular reduction to expose the parameters in a Reduction configuration model. This is an umbrella issue for the remainder of this work.

### Necessary For a Single Reduction
- [x] (PR #23630) #23043 Instrument presenter - Necessary to have a workable Reduction Configuration and to start writing a reduction backend. **(1-2 weeks)**
- [x] ~#23034 Sliced workspace names - Necessary for sliced reductions to work.~
- [x] (PR #24384) #23041 Cross-presenter communication - Necessary to allow disabling controls and syncing across tabs.
- [x] Add plot buttons (PR #25458)
- [x] Enable catalog login
- [x] Implement Get Defaults buttons on the Experiment and Instrument tabs (#23046)
- [ ] Thorough stability testing should be done before the final merge to master

### Necessary For Autoprocessing + Plotting from Reflectometry Interface.
Everything above and:
- [x] #23027 Runs tab - All autoprocessing is currently disabled, a number of presenter methods this feature relied on are no longer sanely implementable, this issue lays the foundations for a clean solution. **(1 week)**

### Would be nice to do.
- [ ] #23067 - Makes Copy+Paste applicable in more circumstances, adds ability to paste rows from one group into another group. *Does not require modification to `JobTreeView` copy+paste*.
- [ ] #23032 - Enables nicer automatic save. **(1 day)**
- [ ] #23049 - Better handling of erroneous input.
- [ ] #23036 - More reliable theta value loading, Improved runs table usability.
- [ ] #23039 - Improved runs table usability.
- [ ] Globally define colours e.g. for invalid inputs, rather than hard-coding them in each view.
- [ ] Check if it's worth tidying up duplicated code such as the `toCsv` and `messageFor` functions which appear in both ExperimentView.cpp and InstrumentView.cpp.
- [ ] Check if it's worth refactoring repeated code like `acceptMainPresenter` into a base class for the tab presenters, and whether we could have a single interface e.g. `ITabPresenter` instead of separate interfaces for each tab presenter.

### Bugs
- [x] In the table, if you copy a group and paste it over a row, the row becomes a group and you get unexpected behaviour. Pasting onto a different level should be disallowed.
- [ ] If you create a new batch, close batch 0, and then create a new batch, you'll have 2 batch 1 tabs.
- [ ] insert a group and then try to delete it. you won't be left with an empty table area as with a new batch window
- [ ] Text in Event Handling, Experiment Settings, and Instrument Settings tabs are a lot smaller than Runs and Save ASCII (Ubuntu 18)
- [ ] In Event Handling -> Uniform slicing you can type a + at the start of the number. For even time slices you cannot type a - at all, but for (sec) slices you can type a - but no numbers after it. This doesn't cause any errors but is confusing and annoying so it would be good to sort out if possible.
- [x] In the Event tab, if you toggle the radio button and then toggle back to Disable Slicing, all of the inputs should be disabled, but the one you selected remains enabled.

**Comment by gemmaguest** [comment]
Closing this issue as remaining tasks have been consolidated into #26025
