### ISSUE TITLE
ISIS Powder: Polaris Feedback

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#23091]
Here is the feedback I received from Polaris regarding ISIS Powder

- [x] File extensions are not being respected in Mantid E.g. `POL12345.s01` opens `POL12345.nxs`. This happens with Data search acrhive, does it happen using the filesystem directly?
- [x] We need to get their current adv. config values and update Mantid to ship these optimal defaults instead
- [x] Absorption corrections require the multiple scattering flag whilst running `focus`, despite multiple scattering not currently being available
- [x] File extension parameter is applied to the vanadium and empty runs (we should use .nxs always)
- [x] Check with Helen that rename workspace group works correctly in the latest release

Long Term:
- [ ] Check all parameters are valid before running the main scripts

**Comment by SamJenkins1** [comment]
I assume the main scripts here refers to stuff like create_vanadium and focus?

**Comment by samueljackson92** [comment]
I would assume that as well.

**Comment by SamJenkins1** [comment]
It appears that the advanced config values in mantid are already up-to-date
