### ISSUE TITLE
ISIS Powder: Pearl Feedback

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#23092]
Here is the feedback I received from Pearl regarding ISIS Powder:

High Priority - Preventing use in production:
- [x] Vanadium spline has a tail where we proceed to divide by small values (this could be resolved by next point)
- [x] Get 0 counts where we "bottom out", instead the very last and first bin should be cropped to deal with them not being properly filled

Normal priority:
- [x] Long mode name does not get appended to the final group workspace name causing confusion
- [x] Separate spline co-eff in adv. config for long mode
- [x] `long_mode` does not emit a warning when it is changed in any way unlike other params 
- [x] Add saving of xye files to focus (specifically `focus_mode = "all"` but really any focus mode that does not do this already.
- [x] Prevent vanadium splines from being written to workspace each time focus is run.
- [x] Allow adjustment of Binning in advance config, similar to polaris

**Comment by samueljackson92** [comment]
For the high priority issues do you have an example script & files that will reproduce the issue?

**Comment by samueljackson92** [comment]
Also perhaps a screenshot of the problem is appropriate.

**Comment by DavidFair** [comment]
Attached is the script which relies on files from Joe to avoid setup:
```python
from isis_powder.pearl import Pearl

pearl_focus = Pearl(user_name="Test",
                          calibration_directory=r"\\olympic\Babylon5\Public\JoeRamsay\PEARL\calib",
                          output_directory=r"\\olympic\Babylon5\Public\JoeRamsay\PEARL\output",
                          config_file=r"\\olympic\Babylon5\Public\JoeRamsay\PEARL\pearl_shared_config.yaml",
                          calibration_mapping_file=r"\\olympic\Babylon5\Public\JoeRamsay\PEARL\pearl_run_mapping.yaml")

pearl_focus.create_vanadium(run_in_cycle=99481)
```

However I'm not seeing it with the above run. We need to contact Nick and ask him for more details such as run number and that he is running the latest version vs an older nightly

**Comment by SamJenkins1** [comment]
I assume the point about spline co-eff is referring to moving 
```
"monitor_spline_coefficient": 20,
"spline_coefficient": 60,
```
out of `general_params` and having two separate versions, one in `long_mode_off_params` and one in `long_mode_on_params`, however I assume that if we're separating them they should have different values?

**Comment by SamJenkins1** [comment]
The high priority issue is thought to be caused by sudden drops at that can occur at either end of the vanadium, for an example of this run
```
from isis_powder import Pearl

config_file_path = r"/home/sjenkins/Documents/Isis Powder/PEARL/pearl_shared_config.yaml"
Pearl_example = Pearl(config_file=config_file_path,user_name="test")
Pearl_example.create_vanadium(run_in_cycle=101508)
```
with these [files](https://github.com/mantidproject/mantid/files/2388752/PEARL.zip) (you'll need to update the paths involved)

**Comment by SamJenkins1** [comment]
further looking into the high priority, the sudden drops seem to first appear after the c++ algorithm MergeRuns is called when creating the vanadium, looking into this further, it seems specifically to happen during the rebin within MergeRuns

**Comment by martyngigg** [comment]
@SamJenkins1 Is this one done now? Can it be closed?

**Comment by SamJenkins1** [comment]
I left it open as the scientists hadn't got round to testing yet, I've had an email saying that they have finally got round to it, so yes I suppose it can now.

**Comment by martyngigg** [comment]
Great stuff!
