### ISSUE TITLE
ISIS Powder - GEM Texturing Roadmap

### ISSUE THREAD

**Issue by DavidFair** [mantidproject/mantid#23170]
The following things need resolving as they are preventing a user from completing texture analysis of their data by mid September:

- [x] The `texture_mode` state is not captured by the vanadium spline fingerprint (this should follow some refactoring work here: #23171 ). 
In `gem_algs` the call to `RunDetails(...)` should set the string "texture" to the `splined_name_list` parameter for it to be appended to the spline name if we are doing textured focusing
- [x] If the splined vanadium contains 0 values with should skip dividing them (to avoid div by zero) in `Focus.py`
- [x] We should help generate a new offsets for GEM. This could be similar to how Pearl does it in `create_cal`
- [x] We save out .nxs files when doing texture and these aren't needed. we should look at removing the save angles flag as it should always happen on texture mode, and adding a save all flag for when they want to save .nxs files. 
- [x] in some cases both the spline and the sample can have a spectrum of just zero's this can lead to nans in the output, which causes maud to fail
