### ISSUE TITLE
Umbrella Issue for Sans usability improvements

### ISSUE THREAD

**Issue by Mantid-Matthew** [mantidproject/mantid#23209]
- [x] The selection bounds for runs is a bit odd 
- [x] Thickness is read from file with too much precision
- [x] No height, width, thickness, Z offset are displayed
- [ ] Mask is only populated after run data is input
- [ ] The type of Tx mon in use us now specified by its spectrum number not (M2/M4) should be M3/M4
- [x] No phi limits are displayed unmasked should be -180 to 180 mirrored
- [x] Save other needs to be added
- [x] Need to update workspace naming to match V1 #23215
- [x] Put 'raw' nxs files in a workspace group so they don't clutter up ADS  
- [x] No Acknowledgment that user file has been loaded (Isn't really needed as this is instant)
- [x] Wavelength and Q labelling in Q, Wavelength tab is wrong when Log bins used i.e. wrong units match old GUI
- [x] Can we tab between fields in the runs table, this should be solved by BatchTreeView
- [x] Process should be process all add process selected
- [x] Plot selected runs does not work, what do you want it to do ?
- [x] Update GUI to use correct detector names everywhere as instrument is changed.
- [ ] Update BeamCentre to use optimizations
- [ ] Windows should not go to back #23294

**Comment by Mantid-Matthew** [comment]
These are now all covered by other issues
