### ISSUE TITLE
Fitting - Interfaces - Umbrella - No existing MVP style FunctionBrowser

### ISSUE THREAD

**Issue by brandonhewer** [mantidproject/mantid#23275]
The FunctionBrowser in Mantid (required for constructing a simultaneous fit through an interface) is currently not in MVP and in cannot be integrated into the QENS fitting interfaces in its current state without significant modifications.

An MVP Function Browser would allow for unit testing of the FunctionBrowser, provide a more general framework for future extensions of the function model and allow integration into the QENS fitting interfaces.

This is an umbrella issue for creating an MVP version of the FunctionBrowser in Mantid.

- [ ] Create the model interface and a (tested) multi-domain implementation of this interface

- [ ] Add a single domain FunctionBrowser modelled after the existing FunctionBrowser along with a presenter to communicate between the model and the browser

- [ ] Add a multiple domain extended version of the FunctionBrowser, the MultiDomainFunctionBrowser, with an associated presenter

- [ ] Add unit tests for the FunctionBrowser and MultiDomainFunctionBrowser (mocking the view and model)
