### ISSUE TITLE
Indirect Interface Needs Tests - Umbrella Issue

### ISSUE THREAD

**Issue by keeeto** [mantidproject/mantid#23463]
**Original reporter:** na

Several aspects of the Indirect Data Analysis interface have been re-written to make them MVP. However, these are currently lacking testing. The features requiring tests are listed below:

- [x] Indirect fitting model - **PR:** #23649
- [x] Indirect fit data - **PR:** #23516
- [x] Indirect fit output - **PR:** #23782
- [x] Indirect fit plot model - **PR:** #23819
- [x] Indirect spectrum selection presenter - **PR:** #23923
- [x] Indirect fit plot presenter - **Issue:** #24065 **PR:** #24070
- [x] Indirect data table presenter - **Issue:** #24095  **PR:** #24096
- [x] Indirect fit data presenter - **Issue:** #24148 **PR:** #24149 
- [x] ConvFit data presenter - **Issue:** #24298 **PR:** #24303 
- [x] JumpFit data presenter - **Issue:** #24298  **PR:** #24303

**Comment by AnthonyLim23** [comment]
@robertapplin when you do your next batch of tests, create a new issue for them then reference this ticket in the new one and put a note on here of the new ticket.
