### ISSUE TITLE
Workbench ready for developer daily use

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/mantid#23592]
A subset of the development team is able to move to the workbench for their daily use when developing new algorithms.

- [x] Supply a script from the command line ~~#23539~~
- [x] Algorithms don't crash the workbench ~~#23637~~
- [ ] Scripts don't crash the workbench

Other random issues that should be fixed

**Comment by peterfpeterson** [comment]
Several developers are using/testing the workbench.
