### ISSUE TITLE
ISIS Powder HRPD Roadmap

### ISSUE THREAD

**Issue by SamJenkins1** [mantidproject/mantid#23731]
- [ ] Check with instrument scientists if the scripts now properly matchup.
- [x] The new scripts were not handling sold angle correction properly.
- [x] Absorption corrections need to take into account that HRPD absorption corrections are not always a cylinder. (Vanadium Multiple Scattering + Slab?)
- [x] Need to deal with prompt pulses, the old scripts apparently handled these, but mantid does not seem to.

**Comment by martyngigg** [comment]
This has become critical to move the HRPD setup from mantid v2.x.
