### ISSUE TITLE
Error Reporter - Roadmap/Todolist

### ISSUE THREAD

**Issue by Pasarus** [mantidproject/mantid#23769]
This is the Error Reporter list of tasks to complete before it's completed.

- [ ] Complete system test integration
- [ ] Review @Mantid-Matthew Pull requests in both the mantid repository and the errorreport repo for File uploads
- [ ] Add screenshot feature and GDPR complaint request for confirmation in the Error reporter using the Qt Screenshot capability

**Comment by Pasarus** [comment]
No longer nessercary
