### ISSUE TITLE
SANS 3.14 Umbrella Ticket

### ISSUE THREAD

**Issue by Mantid-Matthew** [mantidproject/mantid#23952]
This is an umbrella ticket to cover the current sans issues for release 3.14. 

New Gui
=======

To Implement
===========

* [ ] Make reduction window stay on top of main mantidplot window. This requires making the reduction window a child of the main window. The complication is that the window must be removed as a child when unminimised so that it appears in the task bar. For example see how the c++ dockable windows are handled. James/Sarah #23294
* [x] Have the GUI remember the last user file used Rob #23963
* [x] Set save option default to memory Steve #23968
* [x] Add option so save out can work-spaces automatically Najet #23773
* [x] Add angle phi to options column Diego #23969
* [x] Add tooltip for wavelength slicing #23962
* [x] Add button to save out modified table as csv file #23970 
* [x] Display current save location on front screen #23957
* [x] Add sample shape tooltip and auto-completion #23961
* [x] Add load button #23797
* [x] Add process selected button #23795 
* [x] Calibrate and center the files on load. (Currently we just calibrate) #23960 
* [x] Automatically add batch file path to manage directories. #24147
* [x] Update instrument from user file remove instrument combo box. #23971
* [x] Make SANS Errors More Prominent in GUI. #24034 
* [x] Event Slicing < and > syntax not working. #24053 
* [x] Disable compatibility mode #24162 

Small GUI changes
===========
* [x] Settings tab update monitor names for clarity, Monitor normalisation change to scattering, Wavelength adjustment files change to wavelength efficiency files. #24399 
* [x] Change the default update boxes in beam center. Perhaps set instrument specific beam limits. #24399
* [x] Add tool tip for range boxes in diagnostic tab. #24399
* [x] Change default adding mode to event for all but LOQ #24399

To Investigate
===========
* [x] Look into compatibility rebinning issue. #23973
* [x] Add issue for sample transmission (need to talk to Sarah)
* [x] Investigate weird crash with two plus signs. #23974
* [x] Investigate Ctrl+Enter crash #24296
* [x] Radius Max and Min not working on Zoom (need to talk to diego)
* [x] Poke scientists to test beam center finder
* [ ] Speed up event slicing times via reordering workflow. #22897
* [ ] Look into annular integration. #23976
* [ ] SANSGuiDataProcessingAlgorithm error when processing #24282
* [x] Converting SampleShape to string multiple times #24261
* [x] Variable Q binning not loading from user file #24379

General Issues
==========
* [x] Hint tooltip colour not readable on Ubuntu 18 #24347 

Issues post 14/01/19
================
* [ ] RKH files not showing dQ (Steve) #24484
* [ ] Beam-centre finder not working (Diego) #24489
* [x] XML files do not contain unfitted transmissions (Steve) #24424 
* [x] RKH files append by default (James) #24490
* [x] Naming of added files not correct #24491

**Comment by TTitcombe** [comment]
Closing as this is Master ticket for old release
