### ISSUE TITLE
Workbench 'Project' RoadMap/TodoList

### ISSUE THREAD

**Issue by Pasarus** [mantidproject/mantid#24048]
This is a place to track the Workbench Project Saving todos, based on an agreed document produced for this purpose: https://github.com/mantidproject/documents/pull/65

(A tick indicates it is in a PR/merged)

High Priority:
- [x] ~~GUI call to save project and open a file dialog, then starting the script for saving after completion. (See issue #24049)~~
- [x] ~~Saving workspaces to a folder given a path (See issue #24049)~~
- [x] ~~Serializing Interfaces and EncoderFactory and DecoderFactory (See issue #24350)~~
    - [x] ~~Using Encoder and Decoder factories to save and load InstrumentView (See issue #24350)~~
- [x] ~~Saving plots alongside interfaces and workspace names (See issue #24295)~~
- [x] ~~Reopen TableWorkspaces, MatrixWorkspace/Workspace2D and PeakWorkspaces displays. (See issue #24579)~~
- [x] ~~Project Recovery for Workbench (See issue #24656)~~
- [x] ~~Change Project Save behavior to not create a new folder and only accept existing folders being selected. (See issue #24793)~~

Normal Priority:
- [x] ~~Make a worker thread to handle the processing of the Load/Save - This will go hand in hand with the _new_ GUI. (See issue #25325)~~
- [ ] Workspace Groups at present when saved inside of a project end up with all children being saved twice. The first time is when the Group is saved to a .nxs file and the second when their individual workspace is saved.
- [ ] Save Advanced GUI: Ability to choose what to save, interfaces and workspaces etc
   - [ ] Integrate the GUI with the worker thread and a progress bar. Ensure that Users can't do anything but cance until Save or Load is complete.
- [x] ~~Ability to register new encoders using a call similar to the Algorithm declaration and the algorithm manager~~
- [ ] Create user-facing documentation explaining features of project save in workbench
- [x] ~~Some developer documentation on the project save format. It might be a good idea to come up with a schema: https://json-schema.org/understanding-json-schema/about.html~~
- [ ] Make changes to the Project Recovery implementation for MantidPlot and Workbench supporting algorithms to allow wild card searches i.e. `*.Save*.` Currently, we use a predefined list of `ALGS_TO_IGNORE` which are declared in both, the way to fix this is, to dynamically generate the list based on whether or not it contains Save, this future proofs when any other Save algorithm will be added.

Low Priority:
- [ ] Turn off the MainWidget Progress bar when project save/load is doing it's stuff. This is intended to be a minor performance improvement/tidy up.
- [ ] Save more of the preferences for matplotlib plots, that is currently saved, as the initial implementation misses out a few features.
    - [ ] Added saving for `multialignment` on `matplotlib.text` objects - removed from original implementation due to conflicts with `horizontalalignment` and `verticalalignment`
- [ ] Add option to save workspace history instead of actual workspaces to the Advanced GUI effectively the "Generate recovery script" button but saving to a project file. This is dangerous for a lot of workflows and should only be considered if a user is confident in their workflow working.
- [ ] Optimize workspace saving by checking history of workspace's last history entry against last modified time of existent workspace present in the folder, making sure that it does not overwrite present items (Need to add history entry for python changes/make workspace history available to python, probably hidden from GUI)
