### ISSUE TITLE
Live data monitoring improvements on reflectometry GUI

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#24083]
**Original reporter:** Max at ISIS

Some improvements requested when starting live data monitoring from the ISIS Reflectometry GUI:
- [x] (PR #24222) Change the default update interval to 20 seconds
- [ ] #26466 Ideally also add an input box on the GUI (probably next to the start/stop monitor buttons) to specify the interval
- [x] There is a problem where the post-processing algorithm doesn't seem to get run after first starting the monitor, i.e. until the second live data chunk is received, which can be very confusing especially with a long update interval. I'm not sure how difficult it is to fix and whether it is a more general problem with StartLiveData. We should investigate.
- [x] (PR #24221) There is a problem with pyepics on Windows 10. Freddie has provided this [fix](https://github.com/mantidproject/mantid/blob/ea9635ecb8c9b0bc1e8d26fc562f10b1c65dfce2/Framework/PythonInterface/plugins/algorithms/GetLiveInstrumentValue.py) to use cachannel instead. This works but conflicts with DLLs put in the in the mantid installation directory by pyepics which causes it to fall back to caffi instead of the ca libraries on Windows 7 (which is an extra dependency but seems to still work ok).

**Comment by gemmaguest** [comment]
Closing this umbrella issue as there is only one item left which has its own issue
