### ISSUE TITLE
Issues picked up in manual testing

### ISSUE THREAD

**Issue by keeeto** [mantidproject/mantid#24276]
## Issues

This is a list of any issues identified during the manual testing a release cycle. The issues can be checked off as finished. The issues should be assigned levels of priority to decide if the release can proceed.

- [x] **Error reporter** #24259 *High priority no error reporter in OSX/linux nightly*
- [x] **Mantid basic course** #23620 *Low priority fail in docs build*
- [x] **SANS v2** #24245
- [x] **SANS v2** #24243
- [x] **SANS v2** #24239
- [x] **SANS v2** #24220
- [x] **Reflectometry** #24252
- [x] **Reflectometry** #24253
- [x] **Sample transmission** #24224 *Low priority assigned to induction*
- [x] **Engineering diffraction** #24197
- [x] **VSI** #24214 *Potential delay of release - assigned @DTasev*
- [ ] **Filter events** #24274 *Low priority*
- [x] **Multi fitting** #24207 *Docs change required Keith to follow up*
- [x] **Multi fitting** #24208 *Possible docs change Keith*
- [x] **Multi fitting** #24210 *Low priority docs issues Keith*
- [x] **ISIS SANS** #24230 *Low priority has been present for several releases*
- [x] **Muon** #24237 *High priority - needs to go in Anthony is working on this*
- [ ] **Muon** #24258 *Low priority*
- [x] **Indirect interface** #24225 *Low priority docs issue Keith*
