### ISSUE TITLE
Indirect Move over old Wiki Documentation Umbrella Issue

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#24685]
### Description
The Indirect documentation on the old wiki needs to be moved over to the codebase and also updated - it is out of date by several years. 
The moved over documentation should be focused on a basic workflow for each of the interfaces rather than an explanation of each feature within the interface (Documentation for this already exists - although users want this to be clearer and for the explanations to be better). 

**Move over Data Analysis Docs**
- [x] https://www.mantidproject.org/UsingElwin
- [x] https://www.mantidproject.org/Indirect:Indirect_Data_Analysis

**Improved Workflows for:**
- [x] Elwin
- [x] MSDFit
- [x] Iqt
- [x] IqtFit
- [x] ConvFit
- [x] FQFit
- [x] Data Reduction Interfaces

**Data Reduction Docs**
- [x] https://www.mantidproject.org/Indirect:ConvertToEnergy
- [x] https://www.mantidproject.org/Indirect:IndirectDataReduction

Links need updating:
http://www.mantidproject.org/Category:Techniques
http://www.mantidproject.org/Mantid_Examples#Do_it_yourself_examples

### Platforms affected
All

**Comment by robertapplin** [comment]
Finished in #25318
