### ISSUE TITLE
ISIS SANS 4.1 Master Issue

### ISSUE THREAD

**Issue by TTitcombe** [mantidproject/mantid#25357]
### High Priority
Issues we should aim to complete for 4.1. 
* [x] Event slicing output transmission workspaces #24929 
* [x] Fix compatibility mode #23973 
* [x] LARMOR reduction speed #22897
* [x] Mantid Load doesn't include LoadNXCanSAS #25253 
* [x] Added files have issues if bad proton charge run included #25721

### Low Priority
SANS maintenance and easier issues. Complete in any order.
* [x] Must select a file type for memory mode #25637
* [x] CanSAS metadata #25455
* [ ] Metadata in NXCanSAS not correct #22813 
* [x] Batch files to not require output name #25451
* [x] Export Table not working #25438
* [ ] SANS to pass extensions to file finder #24407 
* [x] SANS code refactor #24529 
* [x] Shift command for ZOOM #24747 
* [x] Missing data warning on process #25040 
* [x] Create states error box is unclear #25131 
* [x] Small beam centre finder tab improvements #25251 
* [x] Uncheck canSAS for 2D reduction #25252 
* [ ] Refactor Old/New SANS shared code #25296  
* [x] User and batch file tooltips have unclickable links #25472
* [x] User and batch file folders #25536 
* [x] Add runs save directory default behaviour #25537
* [x] Batch file save order #25538
* [ ] "-add" suffix in SANS processed nexus #25539
* [x] Output notebooks not working #21519
* [ ] Unclear error when reducing merged data in 2D mode #25254
* [x] bug in batch file loading #25694
* [x] Unit test clarity #25558
* [x] Python3 byte/string issue #25705 
* [x] GUI UX minor changes #21975 
* [ ] add sample geometries to batch file #25932
* [x] erase adds rows to table #25930 
* [ ] beam centre finder components to update #25997 

Other "large" issues, such as SESANS and SANS/Refl user files, are not yet ready for development and should be revisited after release 4.1
