### ISSUE TITLE
Clang-tidy Master Issue

### ISSUE THREAD

**Issue by TTitcombe** [mantidproject/mantid#25415]
This issue tracks the clang-tidy fixes which should be carried out in the 4.1/4.2 maintenance period.
Most of these checks have been last run mid-2018 at the earliest, so they should be quick to carry out - assuming we've been sticking to modern C++ programming techniques throughout the release.

Check out **ToolsOverview** in the dev docs for information on how to clang-tidy.

Put your name in a comment with the check you are looking at, and tick it off once you're done.

* [x] modernize-loop-convert
  - MantidPlot: https://github.com/mantidproject/mantid/pull/25273
  - Framework: https://github.com/mantidproject/mantid/pull/25274
  - qt: https://github.com/mantidproject/mantid/pull/25374
* [x] modernize-use-nullptr
  - MantidPlot: https://github.com/mantidproject/mantid/pull/22180
  - Framework: https://github.com/mantidproject/mantid/pull/22176
  - qt: https://github.com/mantidproject/mantid/pull/22181
* [x] modernize-use-using
  - MantidPlot: https://github.com/mantidproject/mantid/pull/22106
  - Framework: https://github.com/mantidproject/mantid/pull/22049
  - qt: https://github.com/mantidproject/mantid/pull/22136
* [x] modernize-use-raw-string-literal
  - MantidPlot: https://github.com/mantidproject/mantid/pull/22165
  - Framework: https://github.com/mantidproject/mantid/pull/22155
  - qt: https://github.com/mantidproject/mantid/pull/22166
* [x] modernize-use-auto
  - MantidPlot: N/A
  - Framework: https://github.com/mantidproject/mantid/pull/14900/ (2016), https://github.com/mantidproject/mantid/pull/26367 (2019)
  - qt: #28320 

To find all related issues: https://github.com/mantidproject/mantid/issues?utf8=✓&q=is%3Aissue+clang-tidy+is%3Aclosed+
