### ISSUE TITLE
C++17 migration umbrella issue

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#26464]
It was agreed that we would aim to move to C++17 after release 4.1 was completed. This is an umbrella issue to track the requirements.

Tasks:

- [x] Move to VS2019 on Windows (#26217)
  - [x] 2 ISIS builders also need to move to Windows 10 (#26219)
  - [x] Changes required to build with VS2019 merged to `master` but still build with 2017
  - [x] Update build scripts to build with 2019
- [x] Drop support for Ubuntu 16.04
  - [x] Builders need to move
- [x] Move to macOS High Sierra as the minimum supported system (#26261) 
  - [x] Builders need to move
- [ ] Update pull request config (if necessary)
- [x] Update clang-format

**Comment by NickDraper** [comment]
Corrected a few of the links to other issues that were muddled
