### ISSUE TITLE
ISIS Reflectometry Full Stack reduction

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#26481]
This is an umbrella for all of the tasks required to provide the full set of reduction algorithms for reflectometry at ISIS.

We need to have a detailed discussion with scientists to set out the requirements for this work. An initial list includes:

- [ ] HIGH Gravity correction #23195  (closed as stale)
- [x] HIGH Detector correction #12524 ?
- [x] HIGH Background subtraction #16456 
- [x] HIGH Polarisation corrections #18823 
- [ ] LOW  Provision for non-rectangular pixels #29016
- [ ] HIGH Normalisation by monitor, monitor integral, transmission etc. (done except #18821)
- [ ] LOW  Graphical detector grouping (see also #15052 and check if #15597 is still relevant)
- [ ] MED  Graphical way to define an area of interest (via a new tab on the GUI)
- [ ] LOW  Mask Q regions in time and/or space.
- [ ] LOW  Finalise conversion to QxQz/KiKf etc. #29016
- [ ] LOW  Option for mask files #29016
- [x] HIGH Correct grouped detector position for multidetector ROI #21742 
- [ ] LOW  Q error bars #18824
