### ISSUE TITLE
Improve unit tests for reflectometry GUI runs tab

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#26512]
Unit testing should be added for the following functionality in the ISIS Reflectometry GUI:
- [x] #26659 Add tests for the live data monitor
- [x] #26517 Move `metadataFromDescription` functionality into the `SearchResult` class and add unit tests for it. Test all possibilities for parsing the description into a group name and theta.
- Expand unit tests for the `RunsPresenter::transfer` functionality:
  - Validation of the row is already done in `ValidateRowTest`.
  - [x] #26518 Add tests in `ReductionJobsMergeTest` to check that jobs get merged correctly via `mergeRowIntoGroup`.
  - [x] #26659 Add a test that the RunsPresenter updates the RunsTablePresenter via a call to `mergeAdditionalJobs`.
  - `mergeAdditionalJobs` itself is already tested in `RunsTablePresenterMergeJobsTest`

**Comment by gemmaguest** [comment]
Child items are all complete
