### ISSUE TITLE
V20 Umbrella Issue for Cleanup from V20

### ISSUE THREAD

**Issue by LamarMoore** [mantidproject/mantid#26767]
- [x] Need to make topics more generic. I.e. take lists of different types of topics and connect to all topics provided by `Facilities.xml` file
- [x] The multi-threading (partitioning) of the event buffer in the `KafkaStreamDecoder` is broken in the `computeGroupBoundaries` (#26858).
- [x] The instrument caching needs to be looked into. When streaming live geometry, updates in instrument geometry are currently ignored in favour of using cached geometry. This will be problematic when geometry is being updated on the fly.
- [x] #26769 The `JSONGeometryParser` should use the `transformation_type` attribute to determine the type of an `NXtransformation` instead of depending on the name of the transformation.
- [x] Applying rotation is bad for empty rotation in `JSONInstrumentBuilder`
- [x] There seems to be an issue with the SaveNexusESS algorithm not saving monitor transformations.

**Comment by OwenArnold** [comment]
Thanks for recording @LamarMoore. Can we look into creating issues for each of these at a time that suits you in the next few weeks.

**Comment by OwenArnold** [comment]
@LamarMoore, your last point ```There seems to be an issue with the SaveNexusESS algorithm not saving monitor transformations```. I have not tried saving/reloading with some of the V20 files that I have. Can you either specify the runs that were problematic so that I can retry, or try it yourself based on `master` which now contains a few fixes relevant.
