### ISSUE TITLE
ILL SANS v6.0

### ISSUE THREAD

**Issue by gvardany** [mantidproject/mantid#26906]
**ALL**

- [x] Allow for multiple transmissions in the workflow - with another wavelength - @darominski  PR #30187
- [x] Define x-pixel-size and y-pixel-size in the IPFs, remove the pixel_height and pixel_width in the loader. Make sure everywhere the instrument parameters are used (solid angle, default q binning, resolutions calculation) @MathieuTillet PR  #30207

**D11 && D22** 
- [x] Loader and MaskBTP @MathieuTillet PR #30320

@gvardany PR #30233
- [x] IDF 
- [x] Dead time and parallax corrections
- [x] Check solid angle method (see above)
- [x] Enable panel separation
- [x] Change the tube direction of D33 (for tube-based masking) 

**D16**

- [x] Expose parameter scan to the drill as an acquisition mode PR #30146

**D22** - @darominski 

- [x] Validate the workflow with horizontal offset (beam stop, transmission, flux), rotation is never done
- [x] Sensitivity from more than one measurement with and without offsets, so without a hole #30294 

**D33** - @gvardany 
- [x] Expose wavelength range to auto process, do CropWorkspaceRagged instead of maskbinsif - PR #30197
