### ISSUE TITLE
Error Stack trace File and Pop-up Umbrella

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#27566]
Increasing Usefulness of the Error Reporter

- [ ] Stack Trace sent through ER system to Support Team #27565 
- [ ] Stack Trace / Error Log Saved as a file to the system
- [ ] ST/EL displayed to the user, at least in exceptional circumstances (crash on launch)
