### ISSUE TITLE
Replace header guards with `#pragma once`.

### ISSUE THREAD

**Issue by Harrietbrown** [mantidproject/mantid#28200]
All cases of header guards `#ifndef` should be replaced with `#pragma once`.
This should be done in chunks for each folder to avoid endless merge conflicts.

**Framework**

- [x] Algorithms #28224
- [x] API #28233
- [x] Beamline #28234
- [x] Catalog #28240
- [x] Crystal #28239
- [x] CurveFitting #28244
- [x] DataHandling #28248
- [x] DataObjects #28250
- [x] Examples (very small) #28254
- [x] Geometry #28257 
- [x] HistogramData #28260
- [x] ICat #28261 
- [x] Indexing #28262
- [x] Kernel #28264 
- [x] LiveData #28270 
- [x] MDAlgorithms & MPIAlgorithms #28271
- [x] Muon #28273 
- [x] Nexus & NexusGeometry #28274
- [x] Parallel #28276
- [x] PythonInterface #28283 
- [x] RemoteAlgorithms & RemoteJobManagers #28284 
- [x] ScriptRepository & SINQ #28285
- [x] TestHelpers & Types #28292
- [x] WorkflowAlgorithms & [`class_maker`](https://github.com/mantidproject/mantid/blob/master/buildconfig/class_maker.py) #28298 

**qt**

- [x] Widgets #28301 
- [x] Icons & paraview_ext #28307
- [x] scientific_interfaces #28309 

**Other**

- [x] MantidPlot #28332 
- [x] Testing #28326 
- [x] Tools #28327

- [ ] Final Check #28365

Once all these are done the final step would be a find replace of the whole project to find any headers that are useing header guards that are outside of Framework.

**Comment by martyngigg** [comment]
As part of this work could we also make sure we update the [`class_maker`](https://github.com/mantidproject/mantid/blob/master/buildconfig/class_maker.py) tool?

**Comment by martyngigg** [comment]
I also just thought that we should update the coding standards page, more specifically [this](http://developer.mantidproject.org/Standards/CPPStandards.html#id5) section. I think it just needs to say something like use `#pragma once` instead of `#ifndef` header guards.

**Comment by Harrietbrown** [comment]
I'll add a line to the `Layout of Header File` section since it doesn't actualy say what sort of guard to use at all.
