### ISSUE TITLE
Build Mantid with Qt5 only

### ISSUE THREAD

**Issue by AndreiSavici** [mantidproject/mantid#28650]
This is an umbrella ticket for building on systems where there is no Qt4 (Ubuntu 20.04). It should prepare for the removal of MantidPlot and supporting code but not remove that yet.

* [x] Build Mantid PR # #28651
* [x] Build tests PR #28651
* [x] Disable Qt4 tests if `-DENABLE_MANTIDPLOT=OFF` #29007 , PR #29013
* [x] UnitTests pass #29390
* [x] Packaging on macOS without MantidPlot (#28833)
* [x] Build documentation/doc tests #28647, PR #29684, #29733 
* [x] Switch to use workbench bundle in DMGInstaller in [mantidinstaller](https://github.com/mantidproject/mantid/blob/master/Testing/SystemTests/scripts/mantidinstaller.py#L289). This will switch the system test CI jobs to use workbench on macOS. Remove the `QT_API=pyqt4` injected variable in [master_systemtests-osx](https://builds.mantidproject.org/view/Master%20Pipeline/job/master_systemtests-osx/configure) and [release_systemtest-osx](https://builds.mantidproject.org/view/Release%20Pipeline/job/release_systemtests-osx/configure) PR #29749 
* [x] Inject `QT_API=pyqt5` on rhel7 wrapper script PR #29921
* [x] Once workbench only can be packaged disable MantidPlot/Vates in build scripts.

The outcome of this is that a build with `-DENABLE_MANTIDPLOT=OFF` should produce a working package with workbench only.

Edited (mgigg: moved to issue #30268)
~~Nice to haves but not required to be able to disable MantidPlot:
* ~~[ ] Systemtests pass #29362 This is not technically required for Qt5 only but these tests fail on Ubuntu 20.04~~
* ~~[ ] Remove code in `#if QT_VERSION < QT_VERSION_CHECK(5, 0, 0)` directives~~
* ~~[ ] Remove Qt4 packages from [RPM/DEB dependencies](https://github.com/mantidproject/mantid/blob/862ceff5356b7a3009e33d5c9062e684f134b8bb/CMakeLists.txt#L388)~~
* ~~[ ] Remove Qt4 from developer packages~~

~~Development docker images will need to have Qt4 installed until we decide to disable MantidPlot on the builds but then they can be removed.~~

**Comment by AndreiSavici** [comment]
With changes in #28651, most of the failing tests are because we force Qt4 testing even if it's not available.

**Comment by martyngigg** [comment]
@AndreiSavici The system test failures on 20.04, with the exception of PVPython, are not all required to be fixed for us to disable MantidPlot on the other platforms.
Would you be happy if we sorted out disabling MantidPlot first? I'm just aware that Release 6.0 is coming and the code freeze is the start of January so getting this is donesooner is probably better.

**Comment by AndreiSavici** [comment]
@martyngigg Fine with me. The ORNL team is looking into those tests anyway, but it can be done after removing MantidPlot

**Comment by martyngigg** [comment]
Brilliant. Thanks for the update.

**Comment by AndreiSavici** [comment]
@martyngigg When the PR with removing MantidPlot is merged, we need to send an email to the user community to say that mantidplotnightly is gone.

**Comment by martyngigg** [comment]
I've moved the remaining parts of this to a new issue that deals with actually removing MantidPlot, #30268, so I'll close this now.
