### ISSUE TITLE
Smoke Testing Umbrella Issue

### ISSUE THREAD

**Issue by DanielMurphy22** [mantidproject/mantid#29608]
This is to keep track of the coverage of smoke tests during the release cycle.
Edit this Issue and Mark beside your OS on the Test you are going to complete.

eg. Windows  - @DanielMurphy22

## Clean/Dirty Install Smoke Tests: #29602
 - [ ] Windows @darominski 
 - [ ] OSX  @gui-co 
 - [ ] Redhat @martyngigg 
 - [x] Ubuntu @MathieuTillet 
 
## Fitting Smoke Tests: #29603
 - [x] Windows @darominski 
 - [x] OSX - @DanielMurphy22 
 - [ ] Redhat - @martyngigg 
 - [ ] Ubuntu
 - [ ] IDaaS (this covers Redhat also) @martyngigg @RichardWaiteSTFC 

## Interface Smoke Tests: #29604
 - [x] Windows  - @sf1919
 - [x] OSX - @DanielMurphy22 
 - [ ] Redhat - @martyngigg 
 - [x] Ubuntu - @DavidFair 
 - [ ] IDaaS (this covers Redhat also) - @martyngigg 

## Plotting Smoke Tests: #29605
 - [x] Windows  @robertapplin 
 - [x] OSX @Matt-Cumber 
 - [ ] Redhat @martyngigg 
 - [x] Ubuntu @MathieuTillet 
 - [ ] IDaaS (this covers Redhat also) @martyngigg @RichardWaiteSTFC 

## Python Smoke Tests: #29606
 - [x] Windows  - @clayton-tom 
 - [x] OSX  @gui-co @gvardany 
 - [ ] Redhat - @martyngigg 
 - [x] Ubuntu - @DavidFair 
 - [ ] IDaaS (this covers Redhat also)  - @martyngigg 

## Workspace/Algorithm Smoke Tests: #29607
 - [x] Windows @DannyHindson 
 - [x] OSX - @gvardany 
 - [ ] Redhat - @martyngigg 
 - [ ] Ubuntu
 - [ ] IDaaS (this covers Redhat also) - @martyngigg
