### ISSUE TITLE
Remove Qt4-only code

### ISSUE THREAD

**Issue by martyngigg** [mantidproject/mantid#30268]
MantidPlot was removed from distribution during the 6.0 development cycle but the code and its dependencies still remain. This is an umbrella issue for removing the Qt4-only code from the codebase.

Remaining tasks:
* [ ] Remove Qt4 references

Completed tasks:
* [x] Remove ifdefs in Qt5 code that supports Qt4 (check for ifdefs looking for qt5 as well as qt4)
  * Remove code in `#if QT_VERSION < QT_VERSION_CHECK(5, 0, 0)` directives #33862
  * Ensure all Qt4 code in pqHelpWindow.h and pqHelpWindow.cxx is removed.
* [x] Remove MantidPlot #30450 and #30460
* [x] Remove paraview/VSI (SaveVTK should stay) (ISIS to arrange) #30500
* [x] Remove `ENABLE_MANTIDPLOT` CMake option - done except in top level cmake file until build scripts are changed #32421
* [x] Remove finders for Qt4 and other dependencies for mantidplot from `buildconfig/CMake` #31209
* [x] ~~Systemtests pass #29362 This is not technically required for Qt5 only but these tests fail on Ubuntu 20.04~~ No longer valid as we are moving to Conda
* [x] Remove Qt4 packages from [RPM/DEB dependencies](https://github.com/mantidproject/mantid/blob/862ceff5356b7a3009e33d5c9062e684f134b8bb/CMakeLists.txt#L388) #30450
* [x] Remove Qt4 from developer packages #32013

**Comment by peterfpeterson** [comment]
This should not be closed

**Comment by martyngigg** [comment]
The final steps are to review if anything is remaining and either finish it or just close this issue.

**Comment by robertapplin** [comment]
I think this can be closed now that #35082 is merged
