### ISSUE TITLE
ILL SANS v6.1

### ISSUE THREAD

**Issue by gvardany** [mantidproject/mantid#30343]
- [x] Passage of shapes (at the moment only sectors) to the integration with an option individual vs. together, possibility to group shapes? (keep an eye on the absolute measures) @MathieuTillet PR #30463 
- [x] Logbook generator @darominski PR #30432 
- [x] More flexible stitching, allow choosing which curve to be the reference (the middle one by default), log and store calculated scale factors, expose manual stitch factors to the user @darominski PR #30571
- [x] Support Solvent as another process type @darominski PR #30660
- [x] Change naming of output workspaces, introduce formats to include distance, collimation and wavelength (technique dependent) @gui-co PR #30567
- [x] Write important information as comment lines in the header of ascii exports (in a spirit of workspace history in case of processed nexus) @gui-co , @darominski  PR #30743
- [x] Rewrite stitching algorithm @gvardany 
- [x] Resolution calculated based on direct beam in analogy to Grasp (gaussian approximation) (wait for scientists decision) @darominski PR #31395 
- [x] Swap Detector 1/2 since May 01 on D22.

**Comment by gvardany** [comment]
DONE.
