### ISSUE TITLE
Improve Release Checklist

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#30663]
### Description
Read through the [release checklist](https://developer.mantidproject.org/ReleaseChecklist.html) and look for ways to improve them. After discussion with Stephen we have come up with a few points we could improve on:

- [ ] Separate the checklist into different categories based on role (makes it easier to follow the checklist based on what role you are playing in the release) i.e. We could have a Technical Release Manager checklist, a Quality Assurance Manager checklist, etc. (`Rob`)
- [x] Investigate whether the python script generating the release notes added a link to the correct release in the `index.rst` of the root directory of the release notes. (`Rob`)
- [ ] Add code snippets for when running a python script to make it easier to understand the format required for each argument (e.g. difficult to know where to use '6.0' or '6.0.0' for one of the arguments). (`Stephen`)
- [ ] Create a jenkins job that can edit `VersionNumber.cmake` and merge it without requiring a gatekeeper. It would mean we won't forget to comment/uncomment the patch number. (`A later consideration`)
