### ISSUE TITLE
Add ROI selector for instrument viewer to reflectometry GUI

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#32034]
As part of #31069, create a tab on the ISIS Reflectometry interface and embed the newly split out instrument viewer display.

- [x] #32096 
- [x] #32125
- [x] Embed the InstrumentDisplay created in #31739 (requires creating an InstrumentActor and ProjectionSurface). See prototype in gemmaguest:experimental/refl_gui_roi_selection. #32490
- [x] Add controls: button to toggle between selection mode and zoom mode (simple rectangular selection is sufficient for now) #32566 
- [x] Create an algorithm to take the selected detectors and sum across banks #32771
- [x] #32772
- [x] Add a way to display or store the selected detectors (e.g. a simple button to display them for now or if not too complex this could be wired straight into the reduction configuration in the reflectometry GUI) 

As part of this, the following tidying is required:

- [x] Remove dead code: getSelectedDetectors is not used

**Comment by gemmaguest** [comment]
The final tasks are now covered in #34238 and #34220 so closing this issue
