### ISSUE TITLE
Sum across banks and plot the result on a contour plot

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#32772]
Sum across banks in the ISIS Reflectometry GUI Preview tab and plot the result.

- [x] Add a method to the `ReflAlgorithmFactory` to run the new algorithm (see #32771). This will need to call functions to convert the model to algorithm properties similar to those in `RowPreprocessingAlgorithm`
- [x] This should save the result in the `PreviewRow`
- [x] Embed the `ContourPreviewPlot`
- [x] When the ROI on the instrument viewer is updated, execute the algorithm using the selected ROI and plot the result #32942
- [x] Add a button to be able to save the plotted workspaces to the ADS #32958

**Comment by gemmaguest** [comment]
This is all done apart from #32942 which is held up due to ADS issues.
