### ISSUE TITLE
Match lookup rows using lookup text when a user processes a row

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#33512]
**Refactoring**

- [x] Refactor the contents of `Experiment::findLookupRow` into a separate class e.g. `LookupRowFinder` and add tests for it
  - [x] Test lookup of exact theta match works
  - [x] Test lookup of different theta but within tolerance works
  - [x] Test lookup of theta outside tolerance fails and uses wildcard row instead
  - [x] Test lookup of theta fails and there is no wildcard row does not match anything
  - [x] Test lookup with empty table
- [x] Refactor the method to take a `Row` instead of the angle
- [x] #33546
- [x] Merge the `LookupRowFinder` method into `LookupTable`

**New feature**

- [x] Add a new field for the regex expression to the `LookupRow` model
- [x] Adjust the `LookupTable` to use the new regex field as well as the angle when looking up a row
  - [x] If both angle and regex are specified then check both. Ensure we do this before checking wildcard rows or rows where the regex is not set.
  - [x] Secondly, if the angle is specified but the regex is not then just check the angle
  - [x] Thirdly, check wildcard rows (where neither the angle or regex is specified)
