### ISSUE TITLE
Conda-forge packages

### ISSUE THREAD

**Issue by Pasarus** [mantidproject/mantid#33528]
- [ ] #33337
- [ ] Evaluate mantid compatibility with the current conda-forge global pinning and create issues like the GSL issue, to update compatibility.
- [ ] Answer: Should we have one repo with all 3 items from one recipe or 3 items with 1 item from one recipe per repo? This also needs a feasibility check with either gitter or as a PR on the conda-forge/staged-recipes.
    - [ ] Make Conda-forge repo for all mantid packages OR
    - [ ] Make Conda-forge repo for mantid
    - [ ] Make Conda-forge repo for mantidqt
    - [ ] Make Conda-forge repo for mantidworkbench

Make a conda-forge repo by following the conda-forge information on the topic. https://conda-forge.org/docs/maintainer/adding_pkgs.html

**Comment by thomashampson** [comment]
We might revist this in the future, but currently there's not enough value in it.
