### ISSUE TITLE
Drop old dependency management (None-conda)

### ISSUE THREAD

**Issue by Pasarus** [mantidproject/mantid#33527]
Dependent on these and all these are dependent on:
- #33445
- #33450
- #33456
- #33522
- #33525

All items that this is dependent on the need to be completed before starting these:
- [ ] #33021 (needed?)
- [x] #33023
- [x] #32088

All previous items need to be completed before we can start working on these:
- [x] Remove the ThirdParty dir and all references from CMake
    - [ ] Archive the third party MSVC dependencies archive.
- [x] Move Jenkins nodes to be basic Jenkins Docker images (If possible)
- [ ] Remove all Ubuntu/Debian packaging work that is not around conda-build
- [ ] Remove all RHEL/CentOS packaging work that is not around conda-build
- [x] Remove anything outside of CONDA_BUILD or CONDA_ENV in CMake where an if CONDA_BUILD or CONDA_ENV is present.
- [x] Turn off the old Jenkins nightly pipeline, PR packaging for system tests, and other outdated Jenkins systems.
