### ISSUE TITLE
Perform live preview reduction when ROI changed

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#34106]
When the reflectometry GUI is notified of a change to an ROI it should run a full reduction on the preview data using the new ROI.

- [x] Link up notifications and run the reduction using `ReflectometryReductionOneAuto`
  - [x] Use the ROI from the region selector as the `ProcessingInstructions` property
  - [x] Use the angle from the Preview tab for the `ThetaIn` property
- [x] Add an Export button so that the result can be viewed in the ADS
- [x] #34209
- [x] #34210
- [x] #34212

**Comment by gemmaguest** [comment]
Closing because all child issues are now closed
