### ISSUE TITLE
EPIC: Preview tab UX improvements

### ISSUE THREAD

**Issue by gemmaguest** [mantidproject/mantid#34220]
- [x] #34239
- [x] #34223
- [x] Ensure all plots are updated when you click Load or change the instrument viewer selection - there seems to be a bug where the reduction is not being run in these cases. **I think this is fixed by the last commit in** https://github.com/mantidproject/mantid/pull/34253
- [x] #34253
- [x] #34270
- [x] #34263
- [x] #34601
- [x] #34606
- [x] #34602
- [x] #34603
- [x] #35264 
- [ ] #35265
- [ ] https://github.com/mantidproject/mantid/issues/35347
- [x] https://github.com/mantidproject/mantid/issues/35348
- [x] https://github.com/mantidproject/mantid/issues/35349
- [ ] https://github.com/mantidproject/mantid/issues/35351
- [x] #35565
- [ ] #35696
- [ ] #35697
- [ ] #35902

**Backlog**
- [ ] Enable the Update button when settings have changed on the other tabs - possibly also feed back to the user some way (perhaps in the statusbar when that is added) that settings have changed and the plots need to be updated. (1)
  - Related to this, there's a minor usability issue if you change the Angle on the Preview tab and do not click Update, it will use the previous angle you had set when you click Apply. This is a bit confusing but actually makes sense with what the reduction is showing. I think we just need to make it more obvious that an Update is required - perhaps highlight the button somehow/make it bigger/put a red label next to it explaining what's happened/update the status bar (when that is added) with red text..? (2)
- [ ] Remove the colorbar from the sliceviewer section and add a button to the instrument view and sliceviewer toolbars to pop up the color bar in a separate window. (8)
- [ ] Display pop-up messages for warnings instead of just outputting them to the log. Currently it is not always obvious when an error has occurred. This will need the message handler passing through to the Preview tab so should be straightforward but involve a fair bit of boilerplate. Tests can also then be added because we can mock the message handler. (3)
- [ ] Currently, loading different data, particularly from a different instrument or detector type, results in confusing axes and ROIs on the plots. I think it can also cause a crash if e.g. an ROI covers spectra that don't exist. We should probably reset the plots' axes and clear the ROIs when reloading data. 
  - We perhaps don't want to lose the ROIs accidentally if re-loading the same/similar workspace, but perhaps we could make it clear that the Load button also resets things (it could be called Load/Clear for example, or perhaps we have a separate Clear button and disable the Load button if the workspace name hasn't changed. It would probably be good to have a way to clear the ROIs anyway). 
 - [x] Sometimes ROI selectors appear selected when they're not, causing confusion over when they can be deleted. This has been observed on the instrument view plot, but we should also check if it's an issue on the slice viewer as well.

**Icebox**

- [ ] The initial layout needs to be tidied up when there is no data loaded (perhaps wait till region selector work is finished because its layout might change to make this easier) 
- [ ] Set an initial ROI to include the whole instrument by default. This would be nice to have but is not high priority. (2)
- [ ] The current selectors are rectangles but we only use the selected height of the rectangle; the width is ignored, which could potentially be confusing. It would be better to have a different selector type to make this more intuitive. Currently low priority.

**Comment by mantid-builder** [comment]
Fixed by #34239

**Comment by robertapplin** [comment]
We still need this @mantid-builder

**Comment by mantid-builder** [comment]
Fixed by #34239
