### ISSUE TITLE
ALFView Epic - Optimisation of Workflow

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#34558]
**Description**
The ALF instrument requires frequent manual adjustments after each (< 1 minute) run to realign the single crystal(s). These adjustments require us to know how much we should rotate the sample by (`R`). This can be calculated from the out of plane angle, `V`, and two theta, `2θ`, obtained from the ALFView interface.

```
R = V / (2sinθ)
```

Many scientists still use ALFplus, a custom-made interface which is near end of life, due to its simpler workflow. The ALFView could be optimised for a better user experience to encourage a transition to use it over ALFplus.

**Current workflow**

1) Load data [ALF82301](file:///home/mlc47243/Documents/other-documents/ALFView/ALF82301.zip)
2) Click on `Pick` tab
3) Click on `Add single crystal peak` icon so that the little graph doesn’t keep changing
4) Click on the peak
5) Expand `Rebin` section. Filter by d-spacing range (optional) `5.5,0.01,6`
6) Expand `Plotting detector spectra` section
6) Click on `Select whole tube` icon
7) Right click on little graph and select `Integrate` rather than sum
8) Right click on little graph again and select `Axis->Out of plane angle`
9) Right click on peak of interest and select `Extract Single Tube`
10) If averaging, then right click on each tube -> select `Add to average`. Wrong click requires starting over
11) Press `Update Estimate` button
12) Press `Fit` button
13) Scroll down to find peak centre value (V)
14) Return to pick tab and try to identify horizontal 2theta of tube from text box info
15) Calculate average 2theta if multiple tubes were selected
15) Manually calculate R

**Plan**
- [x] #34638
- [x] #34626
- [x] https://github.com/mantidproject/mantid/issues/34679
- [x] https://github.com/mantidproject/mantid/issues/34604
- [x] https://github.com/mantidproject/mantid/issues/34605
- [x] #34568
- [x] #34569
- [x] #34823
- [x] #34835
- [x] #34846
- [x] #34824

**Bugs**
- [x] #34564
- [x] #34625
- [x] #34663
- [x] https://github.com/mantidproject/mantid/pull/34816
- [x] #34909 

**User experience**
- [x] Only show the useful buttons on the Pick tab
- [x] Increase size of handles on region selectors
- [x] Increase sensitivity of peak peaker and other markers to 5
- [x] Show the number of extracted tubes? Along with their two thetas?
- [x] Reshuffle of analysis pane
- [X] Set background color of PreviewPlot to the color of the GUI

**Comment by robertapplin** [comment]
Completed
