### ISSUE TITLE
Fix failing doc-tests

### ISSUE THREAD

**Issue by peterfpeterson** [mantidproject/mantid#35073]
After the following doc-tests are fixed, running them should be re-enabled on the osx build. 

To coordinate work, please add your name/facility to items when work is started.

From doing a full run locally the following doctests are failing for me (someone should verify):

# Todo
- [x] algorithms/ConvolveWorkspaces-v1.rst
- [x] algorithms/CorrectTOFAxis-v1.rst - 2 failures test
- [x] algorithms/CreateEPP-v1.rst
- [x] algorithms/CreateSampleWorkspace-v1.rst
- [x] algorithms/FindEPP-v2.rst
- [x] algorithms/FindPeaks-v1.rst
- [x] algorithms/Fit-v1.rst
- [x] algorithms/FitGaussian-v1.rst
- [x] algorithms/FitPeaks-v1.rst
- [x] algorithms/GetDetectorOffsets-v1.rst
- [x] algorithms/HB3AIntegrateDetectorPeaks-v1.rst
- [x] algorithms/IntegrateEPP-v1.rst
- [x] algorithms/Integration-v1.rst
- [x] algorithms/LoadEMU-v1.rst
- [x] algorithms/LoadILLTOF-v2.rst
- [x] algorithms/LoadSESANS-v1.rst- Test and cleanup code
- [x] algorithms/MatchPeaks-v1.rst
- [x] algorithms/MayersSampleCorrection-v1.rst
- [x] algorithms/MSDFit-v1.rst
- [x] ~~algorithms/SaveVulcanGSS-v1.rst~~ Algorithm hard deprecated, usage code removed. 
- [x] techniques/PolarisedDiffractionILL.rstsave
- [x] algorithms/EnggSaveGSASIIFitResultsToHDF5-v1.rst
- [x] techniques/ReflectometryILL.rst
- [x] algorithms/PolDiffILLReduction-v1

# Not erroring (for @ConorMFinn on Ubuntu 18.04)
- [x] algorithms/ConvertSnsRoiFileToMask-v1.rst - test and cleanup code
- [x] algorithms/CorelliCalibrationDatabase-v1.rst
- [x] algorithms/EnggCalibrateFull-v1.rst - test and cleanup code
- [x] algorithms/LoadDetectorsGroupingFile-v1.rst- 2 failures test - 2 cleanup code failures
- [x] algorithms/LoadNXcanSAS-v1.rst
- [x] algorithms/SaveDaveGrp-v1.rst
- [x] algorithms/SaveFITS-v1.rst- just cleanup code
- [x] algorithms/SaveMD-v1.rst
- [x] algorithms/SaveMD-v2.rst - test and cleanup code
- [x] algorithms/SaveNXcanSAS-v1.rst
- [x] algorithms/SpatialGrouping-v1.rst- Test and cleanup code
- [x] algorithms/SpecularReflectionPositionCorrect-v2.rst

**Comment by gecage952** [comment]
From doing a full run locally the following doctests are failing for me (someone should verify):
- [ ] algorithms/ConvertSnsRoiFileToMask-v1.rst - test and cleanup code
- [ ] algorithms/ConvolveWorkspaces-v1.rst
- [ ] algorithms/CorelliCalibrationDatabase-v1.rst
- [ ] algorithms/CorrectTOFAxis-v1.rst - 2 failures test
- [ ] algorithms/CreateEPP-v1.rst
- [ ] algorithms/CreateSampleWorkspace-v1.rst
- [ ] algorithms/EnggCalibrateFull-v1.rst - test and cleanup code
- [ ] algorithms/FindEPP-v2.rst
- [ ] algorithms/FindPeaks-v1.rst
- [ ] algorithms/Fit-v1.rst
- [ ] algorithms/FitGaussian-v1.rst
- [ ] algorithms/FitPeaks-v1.rst
- [ ] algorithms/GetDetectorOffsets-v1.rst
- [ ] algorithms/HB3AIntegrateDetectorPeaks-v1.rst
- [ ] algorithms/IntegrateEPP-v1.rst
- [ ] algorithms/Integration-v1.rst
- [ ] algorithms/LoadDetectorsGroupingFile-v1.rst- 2 failures test - 2 cleanup code failures
- [ ] algorithms/LoadEMU-v1.rst
- [ ] algorithms/LoadILLTOF-v2.rst
- [ ] algorithms/LoadNXcanSAS-v1.rst
- [ ] algorithms/LoadSESANS-v1.rst- Test and cleanup code
- [ ] algorithms/MatchPeaks-v1.rst
- [ ] algorithms/MayersSampleCorrection-v1.rst
- [ ] algorithms/MSDFit-v1.rst
- [ ] algorithms/SaveDaveGrp-v1.rst
- [ ] algorithms/SaveFITS-v1.rst- just cleanup code
- [ ] algorithms/SaveMD-v1.rst
- [ ] algorithms/SaveMD-v2.rst - test and cleanup code
- [ ] algorithms/SaveNXcanSAS-v1.rst
- [ ] algorithms/SaveVulcanGSS-v1.rst - test and cleanup code
- [ ] algorithms/SpatialGrouping-v1.rst- Test and cleanup code
- [ ] algorithms/SpecularReflectionPositionCorrect-v2.rst
- [ ] techniques/PolarisedDiffractionILL.rst

**Comment by AnthonyLim23** [comment]
algorithms/LoadEMU-v1.rst is doing the wrong thing. It should not include monitors https://github.com/mantidproject/mantid/issues/35118

**Comment by peterfpeterson** [comment]
@AnthonyLim23 EMU is an instrument at ANSTO

**Comment by AnthonyLim23** [comment]
@geishm-ansto should LoadEMU include monitors?

**Comment by geishm-ansto** [comment]
@AnthonyLim23 EMU did not include a beam monitor. It is a backscattering instrument with a doppler shift and the scientist relied on the direct measurements as a pseudo-monitor for flux normalisation.

**Comment by AnthonyLim23** [comment]
@geishm-ansto so does the algorithm need changing to not include the monitors?

**Comment by ConorMFinn** [comment]
@geishm-ansto The instrument definition includes this extra bank, which are loaded in as monitors. Is this new/expected? 
![image](https://user-images.githubusercontent.com/47181718/216041576-6ef19e69-e585-46a3-83d4-ac8daa4d9e77.png)

**Comment by geishm-ansto** [comment]
@ConorMFinn The history with the EMU instrument is that the (pseudo beam monitor) tube was always there but without electronics connected so there was no data and the original IDF did not include the spare tube. Now that it is active the IDF was updated. The early data files could be loaded with the new IDF but have zero events recorded for that tube. When the change was submitted the doc-tests passed at the time (?). Your change sounds fine, thanks.
