### ISSUE TITLE
D16B: cycle 213 commissioning issues

### ISSUE THREAD

**Issue by darominski** [mantidproject/mantid#35092]
A number of issues have been found in the commissioning of the new ILL instrument, D16B. These are namely:
- [x] Instrument geometry contains only one monitor, while the instrument definitely has two. Fixed by #35206
- [x] Users would like to be able to apply the sensitivity map as early as possible to correct the raw data, possibly not seeing truly raw data at all. Fixed by #35206 
- [x] Number of corrections  to the Simple scan viewer interface. Fixed by #35206
     - [x] Fitting should be used instead of calculating centre-of-mass in ROI
     - [x] The advanced option does not work when absorber, container, nor default mask properties are filled 
- [x] Log `timer`, defined to be merged, does not exist, and should be replaced by detector count.  Fixed by #35136 

**Platform/Version (please complete the following information):**
 - Mantid Version 6.5

**Additional context**
