### ISSUE TITLE
ALFView future improvements and recommendations

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#35115]
**ALFView future recommendations**
- [x] https://github.com/mantidproject/mantid/issues/35114
- [ ] LSS has done some work to port the standard python plot widget into the Refl GUI. This is more interactive than the `PreviewPlot` widget that is currently being used in ALFView. We might want to replace the `PreviewPlot` with one of these widgets if it is more fit for purpose. Talk to Rachel and/or Conor
- [x] Issue opened  https://github.com/mantidproject/mantid/issues/34821

**Comment by robertapplin** [comment]
This should stay open

**Comment by robertapplin** [comment]
I have done some investigating into using the LSS python plot and I believe there would not be much benefit gained from using it instead of the `PreviewPlot` widget. The `PreviewPlot` widget also works with Peak markers, and this doesn't appear true for the LSS python plot. Therefore closing this issue as everything has either been finished, investigated, or a new issue has been opened
