### ISSUE TITLE
Modernise the embedded plots in the Indirect/Inelastic GUIs

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#36347]
**Is your feature request related to a problem? Please describe.**
The embedded plots used in the Indirect and Inelastic GUIs feel a little bit clunky and not very interactive (apart from the ability to move markers around the plots). Users have requested for there to be a toolbar of options that allow zooming, panning across the plots, and adding grids to the plots e.g.
![image](https://github.com/mantidproject/mantid/assets/40830825/5a080efa-268e-40c0-901b-a484f3d771eb)

The embedded plots in these interfaces use something called the `PreviewPlot` widget.

**Describe the solution you'd like**
I don't want to just cobble an options toolbar onto the top of the current `PreviewPlot` widget. I think the code for this widget should first be reviewed and made to be more of a light-weight implementation of a matplotlib plot in C++. The mechanism for adding markers onto this light-weight plot should then be made to be more concrete - currently the implementation feels like a poorly integrated appendage (I know this because I did it on my industrial placement :/ ). I would then like to carefully add a toolbar onto the plot in a way that is configurable. The plan I am considering:

- [ ] Review and refactor the `PreviewPlot` widget to make it more light-weight, less clunky. Might want to rename this widget too
- [ ] Improve the mechanism for adding markers so that it feels more concrete
- [ ] Add the ability to have a toolbar which is configurable, onto the top of the plot.

It would also be nice if the light-weight preview plot was more configurable, so that it can have multiple subplots on the canvas. This might help with the space issues we are experiencing on the Data Analysis GUI. The Fit and difference plots are currently squished together and do not have much space. Being able to have two subplots on the same canvas would make this spacing issue easier to solve.
