### ISSUE TITLE
Move indirect interface files

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#36422]
## Description
We want to re-organise the interfaces found in the Indirect category. As part of this re-organisation, we want to move some interfaces to the new Inelastic category (such as Bayes, Data Analysis, Corrections), and we want to move their files to the relevant directories. As part of moving these files, we want to move them into a better organised structure so its easier to see the divide between different interfaces.

This issue is an epic to keep track of this move of interface files.

**Bayes**
- [x] #36412

**Corrections**
- [x] #36355

**Data Manipulations**
- [x] #36323

**Data Analysis**
- [x] #35665

**Other**
To do the following re-organisation, we will need the `Indirect` interface target to link to the `Inelastic` interface target. Currently, this is the other way around (i.e. `Inelastic` interface target currently links to the `Indirect` interface target).

- [ ] The Simulation, Diffraction and Tools Indirect interfaces should be moved to subfolders in the Indirect directory
- [ ] Move Settings widget file to inelastic directory. In its own folder, maybe `Inelastic/Common/Settings/`
- [ ] The `IndirectInterface` file should be moved to the `Inelastic` folder inside a `Common` folder
- [ ] Move the `AddWorkspaceDialog`'s to the `Inelastic/Common/` location
