### ISSUE TITLE
Rename indirect interface files

### ISSUE THREAD

**Issue by robertapplin** [mantidproject/mantid#36589]
**Description:**
We want to rename some of the interfaces, and the classes/files related to these classes. This issue is an epic to keep track of this  rename of interface files.

- [x] #36363 
- [ ] The `IndirectInterface` file should be renamed to `InelasticInterface`
- [x] The files and classes in the `Inelastic/Analysis` folder should have `Indirect` removed from their name. https://github.com/mantidproject/mantid/pull/37035
- [x] #37075
- [ ] The files and classes in the `Indirect/*` folders should have `Indirect` removed from their name.

**Comment by sf1919** [comment]
@robertapplin @adriazalvarez should this have been closed?

**Comment by robertapplin** [comment]
> @robertapplin @adriazalvarez should this have been closed?

Yes this should be complete now, thanks

**Comment by sf1919** [comment]
I will change the milestone then
