### ISSUE TITLE
Engin-X - Umbrella Issue/ticket - up to a first basic GUI

### ISSUE THREAD

**Issue by PeterParker** [mantidproject/mantid#9213]
This issue was originally [TRAC 8368](http://trac.mantidproject.org/mantid/ticket/8368)

This ticket is blocked by : 
 - [X] [TRAC8760](http://trac.mantidproject.org/mantid/ticket/8760)
 - [X] [TRAC9783](http://trac.mantidproject.org/mantid/ticket/9783)
 - [X] [TRAC9784](http://trac.mantidproject.org/mantid/ticket/9784)
 - [X] [TRAC9789](http://trac.mantidproject.org/mantid/ticket/9789)
 - [X] [TRAC9790](http://trac.mantidproject.org/mantid/ticket/9790)
 - [X] [TRAC9791](http://trac.mantidproject.org/mantid/ticket/9791)
 - [X] [TRAC10587](http://trac.mantidproject.org/mantid/ticket/10587)- Issue #11429 - use ConvertUnits wherever possible
 - [X] [TRAC10589](http://trac.mantidproject.org/mantid/ticket/10589) - became duplicate
 - [x] [TRAC10907](http://trac.mantidproject.org/mantid/ticket/10907) - Issue #11746 - FindPeaks behavior with expected peaks
 - [X] [TRAC10909](http://trac.mantidproject.org/mantid/ticket/10909) - Issue #11748 - EnginXFitPeaks output table
 - [x] [TRAC10910](http://trac.mantidproject.org/mantid/ticket/10910) - Issue #11749 - expected peaks loading
 - [X] [TRAC10921](http://trac.mantidproject.org/mantid/ticket/10921) - Issue  #11760 - unit tests
 - [X] [TRAC10967](http://trac.mantidproject.org/mantid/ticket/10967) - Issue #11806 - EnginXCalibrate output table
 - [X] [TRAC10968](http://trac.mantidproject.org/mantid/ticket/10968) - Issue  #11807 - bank interpretation (dupl).
 - [x] [TRAC10969](http://trac.mantidproject.org/mantid/ticket/10969) - Issue  #11808 - bank interpretation
 - [x] [TRAC11588](http://trac.mantidproject.org/mantid/ticket/11588) - Issue #12426 - add Vanadium
 - [x] [TRAC11770](http://trac.mantidproject.org/mantid/ticket/11770) - Issue #12608 - mock up for first GUI
 - [x] [TRAC11771](http://trac.mantidproject.org/mantid/ticket/11771) - Issue #12609 - save calibration file
 - [ ] [TRAC11772](http://trac.mantidproject.org/mantid/ticket/11772) - Issue #12610 - first GUI
 - [x] [TRAC11773](http://trac.mantidproject.org/mantid/ticket/11773) - Issue #12611 - save .par files as needed
 - [x] [TRAC11862](http://trac.mantidproject.org/mantid/ticket/11862) - Issue #12700 - apply calibration from EnginXCalibrate full to input workspace detector positions.
 - [x] Issue #12926, use `InputWorkspace` input properties in all EnginX algorithms.
 - [x] issue #13184, add EnggVanadiumCorrections algorithm.

An "umbrella" ticket for any work to be done for Engin-X.

2015/06/22: edited with new github issue numbers and current status.

**Comment by FedeMPouzols** [comment]
I'm adding new EnginX issues/tickets that are not listed here. I'm thinking that this umbrella issue should be closed when we get the first basic GUI (which also implies that we'll have a certain consistent state for all the EnginX algorithms). After that we could make another umbrella for the next steps, if needed.
