### ISSUE TITLE
SANS2D Tube Detectors - Masking Umbrella Ticket

### ISSUE THREAD

**Issue by mantid-builder** [mantidproject/mantid#9691]
sans_feature
This issue was originally [TRAC 8847](http://trac.mantidproject.org/mantid/ticket/8847)

Original Reporter: Gesner Passos

This ticket is blocked by : 
- [X] [TRAC8972](http://trac.mantidproject.org/mantid/ticket/8972)
- [ ] [TRAC9146](http://trac.mantidproject.org/mantid/ticket/9146)
- [X] [TRAC9204](http://trac.mantidproject.org/mantid/ticket/9204)
- [ ] [TRAC9348](http://trac.mantidproject.org/mantid/ticket/9348)

This ticket is blocks :  [TRAC8921](http://trac.mantidproject.org/mantid/ticket/8921)

Umbrella ticket used to cover all work to support masking the new SANS2D tube detectors.

Child of http://trac.mantidproject.org/mantid/ticket/8921, which covers all work necessary for the new layout of the instrument.

**Comment by Mantid-Matthew** [comment]
It is likely that ROI and mask combined complete this ticket. I will double check with scientists.
