### ISSUE TITLE
SANS2D Tube Detectors - Umbrella Ticket

### ISSUE THREAD

**Issue by mantid-builder** [mantidproject/mantid#9764]
sans_feature
This issue was originally [TRAC 8921](http://trac.mantidproject.org/mantid/ticket/8921)

Original Reporter: Gesner Passos

This ticket is blocked by : 
- [X] [TRAC8844](http://trac.mantidproject.org/mantid/ticket/8844)
- [X] [TRAC8845](http://trac.mantidproject.org/mantid/ticket/8845)
- [ ] [TRAC8847](http://trac.mantidproject.org/mantid/ticket/8847)
- [X] [TRAC8848](http://trac.mantidproject.org/mantid/ticket/8848)
- [X] [TRAC8906](http://trac.mantidproject.org/mantid/ticket/8906)
- [X] [TRAC9333](http://trac.mantidproject.org/mantid/ticket/9333)

This ticket is to keep track of the work to do to have the SANS2D tube working.

**Comment by AntonPiccardoSelg** [comment]
Can be closed, cyclical ticket
